### ISSUE TITLE
Camera Not Opening ?

### ISSUE THREAD

**Issue by developeralp** [begeekmyfriend/yasea#120]
Hello everyone,
Thanks for this great library.

When I start app camera not opening / previewing..

When I click "publish" button , I can't see any differences.

My phone's motherboard : MTK6589 
Media Server : Red5 

Error log : 

at net.ossrs.yasea.SrsPublisher.startCamera(SrsPublisher.java:227)
at net.ossrs.yasea.SrsPublisher.startEncode(SrsPublisher.java:55)
at net.ossrs.yasea.SrsPublisher.startPublish(SrsPublisher.java:84)
at net.ossrs.yasea.MainActivity$1.onClick(MainActivity.java:85)

**Comment by developeralp** [comment]
Any ideas ? :(

**Comment by begeekmyfriend** [comment]
Comment out [setDefaultUncaughtExceptionHandler](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/yasea/MainActivity.java#L262-L279) and show me the exception.

But remember out-dated machine is not good enough for live encoding. You will learn to put up with the low FPS.

**Comment by begeekmyfriend** [comment]
M ~0lb
B

**Comment by developeralp** [comment]
Tried release code (v.1.3) and latest updated project on another device and it work like charm ! 
-also v1.3 worked with mtk6589

**Comment by begeekmyfriend** [comment]
It doesn't help.what I need is debug information

**Comment by developeralp** [comment]
I can't get any errors but debug is here : https://cl1p.net/yaseadebug

**Comment by developeralp** [comment]
Also , I will try debug as you said in 2-3 hours.
(I have two mtk6589 , one worked with v 1.3 , other one not worked 15 hours ago.)

**Comment by developeralp** [comment]
Here debug : 

`09-09 18:10:21.658 25832-25832/net.ossrs.yasea E/CameraFramework: Invalid size parameter string=1280*720
09-09 18:10:21.664 25832-25832/net.ossrs.yasea E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: net.ossrs.yasea, PID: 25832
                                                                 java.lang.IllegalArgumentException: Unsupported resolution 1280x720
                                                                     at net.ossrs.yasea.SrsPublisher.startCamera(SrsPublisher.java:196)
                                                                     at net.ossrs.yasea.SrsPublisher.startEncode(SrsPublisher.java:55)
                                                                     at net.ossrs.yasea.SrsPublisher.startPublish(SrsPublisher.java:84)
                                                                     at net.ossrs.yasea.MainActivity$1.onClick(MainActivity.java:76)
                                                                     at android.view.View.performClick(View.java:4463)
                                                                     at android.view.View$PerformClick.run(View.java:18789)
                                                                     at android.os.Handler.handleCallback(Handler.java:808)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                     at android.os.Looper.loop(Looper.java:193)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5307)
                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:831)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:647)
                                                                     at dalvik.system.NativeStart.main(Native Method)`

**Comment by developeralp** [comment]
Solved :+1: 

Problem  : Unsupported  camera preview size 

How to solve ? 

In SrsPublisher.java  , startCamera() method 

after `Camera.Size size = mCamera.new Size(mEncoder.getPreviewWidth(), mEncoder.getPreviewHeight());` line

 I added a method and it does , gets camera previw sizes , adds it to <pair>list  , calculates and gets best size for camera..
(using android.util.Pair)

Also , you should comment that codes in startCamera() method 

```
     /*   Camera.Size size = mCamera.new Size(mEncoder.getPreviewWidth(), mEncoder.getPreviewHeight());
        if (!params.getSupportedPreviewSizes().contains(size) || !params.getSupportedPictureSizes().contains(size)) {
            Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(),
                    new IllegalArgumentException(String.format("Unsupported resolution %dx%d", size.width, size.height)));
        }*/

```

**Comment by begeekmyfriend** [comment]
Fixed https://github.com/begeekmyfriend/yasea/commit/33f50ae729e7283122bc2d365c6ea3eadc9a42ba
Thank you.
