### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: Didn't find class "net.ossrs.yasea.SrsEncoder" on path: DexPathList[[zip file "/data/app/com.example.app-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.example.app-1, /vendor/lib, /system/lib]]

### ISSUE THREAD

**Issue by Kishore1224** [begeekmyfriend/yasea#124]
Hi

Thanks for your Library and your effort.

am facing issue when i change the package name. can you give me the solution to overcome this issue..

Please check the Log..

FATAL EXCEPTION: main
Process: com.example.app, PID: 27548
java.lang.NoClassDefFoundError: net/ossrs/yasea/SrsEncoder
at java.lang.Runtime.nativeLoad(Native Method)
at java.lang.Runtime.doLoad(Runtime.java:435)
at java.lang.Runtime.loadLibrary(Runtime.java:363)
at java.lang.System.loadLibrary(System.java:526)
at com.example.app.SrsEncoder.<clinit>(SrsEncoder.java:538)
at com.example.app.SrsPublisher.<init>(SrsPublisher.java:40)
at com.example.app.MainActivity.<init>(MainActivity.java:38)
  at java.lang.Class.newInstanceImpl(Native Method)
Caused by: java.lang.ClassNotFoundException: Didn't find class "net.ossrs.yasea.SrsEncoder" on path: DexPathList[[zip file "/data/app/com.example.app-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.example.app-1, /vendor/lib, /system/lib]]
           at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:67)
           at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
            at java.lang.Runtime.nativeLoad(Native Method) 
             at java.lang.Runtime.doLoad(Runtime.java:435) 
              at java.lang.Runtime.loadLibrary(Runtime.java:363) 
              at java.lang.System.loadLibrary(System.java:526) 
             at com.example.app.SrsEncoder.<clinit>(SrsEncoder.java:538) 
              at com.example.app.SrsPublisher.<init>(SrsPublisher.java:40) 
              at com.example.app.MainActivity.<init>(MainActivity.java:38)

**Comment by begeekmyfriend** [comment]
Change [this](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/libenc/jni/libenc.cc#L345) and `ndk-build` the so file.

**Comment by begeekmyfriend** [comment]
Change [this](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/libenc/jni/libenc.cc#L345) and `ndk-build` the so file.

**Comment by Kishore1224** [comment]
Hi
Thanks for your reply..

i changed in **src/main/libenc/jni/libenc.cc**
Can you explain how to change **ndk-build the so file**
