### ISSUE TITLE
java.net.SocketException: sendto failed: EPIPE (Broken pipe)

### ISSUE THREAD

**Issue by VolodymyrCj** [begeekmyfriend/yasea#140]
我用的最新的版本，推流大概5s时，就报错，报错详细内容如下：
09-21 09:48:01.081 25849-26027/net.ossrs.yasea E/AndroidRuntime: FATAL EXCEPTION: Thread-879
                                                                 Process: net.ossrs.yasea, PID: 25849
                                                                 java.net.SocketException: sendto failed: EPIPE (Broken pipe)
                                                                     at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:542)
                                                                     at libcore.io.IoBridge.sendto(IoBridge.java:511)
                                                                     at java.net.PlainSocketImpl.write(PlainSocketImpl.java:500)
                                                                     at java.net.PlainSocketImpl.-wrap1(PlainSocketImpl.java)
                                                                     at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:266)
                                                                     at java.io.BufferedOutputStream.flushInternal(BufferedOutputStream.java:185)
                                                                     at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:85)
                                                                     at net.ossrs.yasea.rtmp.io.RtmpConnection.sendRtmpPacket(RtmpConnection.java:435)
                                                                     at net.ossrs.yasea.rtmp.io.RtmpConnection.publishAudioData(RtmpConnection.java:397)
                                                                     at net.ossrs.yasea.SrsRtmpPublisher.publishAudioData(SrsRtmpPublisher.java:58)
                                                                     at net.ossrs.yasea.SrsFlvMuxer.sendFlvTag(SrsFlvMuxer.java:142)
                                                                     at net.ossrs.yasea.SrsFlvMuxer.access$500(SrsFlvMuxer.java:47)
                                                                     at net.ossrs.yasea.SrsFlvMuxer$1.run(SrsFlvMuxer.java:183)
                                                                     at java.lang.Thread.run(Thread.java:818)
                                                                  Caused by: android.system.ErrnoException: sendto failed: EPIPE (Broken pipe)
                                                                     at libcore.io.Posix.sendtoBytes(Native Method)
                                                                     at libcore.io.Posix.sendto(Posix.java:211)
                                                                     at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:278)
                                                                     at libcore.io.IoBridge.sendto(IoBridge.java:509)
                                                                     at java.net.PlainSocketImpl.write(PlainSocketImpl.java:500) 
                                                                     at java.net.PlainSocketImpl.-wrap1(PlainSocketImpl.java) 
                                                                     at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:266) 
                                                                     at java.io.BufferedOutputStream.flushInternal(BufferedOutputStream.java:185) 
                                                                     at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:85) 
                                                                     at net.ossrs.yasea.rtmp.io.RtmpConnection.sendRtmpPacket(RtmpConnection.java:435) 
                                                                     at net.ossrs.yasea.rtmp.io.RtmpConnection.publishAudioData(RtmpConnection.java:397) 
                                                                     at net.ossrs.yasea.SrsRtmpPublisher.publishAudioData(SrsRtmpPublisher.java:58) 
                                                                     at net.ossrs.yasea.SrsFlvMuxer.sendFlvTag(SrsFlvMuxer.java:142) 
                                                                     at net.ossrs.yasea.SrsFlvMuxer.access$500(SrsFlvMuxer.java:47) 
                                                                     at net.ossrs.yasea.SrsFlvMuxer$1.run(SrsFlvMuxer.java:183) 
                                                                     at java.lang.Thread.run(Thread.java:818)

**Comment by begeekmyfriend** [comment]
服务器那边的问题

**Comment by VolodymyrCj** [comment]
但是我用1.2版本同样服务器没有出现该问题

**Comment by begeekmyfriend** [comment]
此一时彼一时

**Comment by VolodymyrCj** [comment]
说的好！
话说SRS出了问题吗，不好推流了，所以在乐视申请了个rtmp网址

**Comment by begeekmyfriend** [comment]
可能yasea下载的人太多，把SRS公网搞瘫了，我把readme改掉吧

**Comment by VolodymyrCj** [comment]
。。论SRS是如何被搞垮的
