### ISSUE TITLE
eglChooseConfig failed

### ISSUE THREAD

**Issue by yuelvic** [begeekmyfriend/yasea#200]
java.lang.IllegalArgumentException: eglChooseConfig failed
                                                                         at android.opengl.GLSurfaceView$BaseConfigChooser.chooseConfig(GLSurfaceView.java:889)
                                                                         at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1064)
                                                                         at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1447)
                                                                         at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1286)

When attempting to run sample app

**Comment by begeekmyfriend** [comment]
Have you modified the original code? Or what is you phone?

**Comment by yuelvic** [comment]
No. It's an Oppo neo 5 - android lollipop

**Comment by begeekmyfriend** [comment]
That is strange. It is the SDK source of `GLSurfaceView.java` in which the egl config is in default setting.

**Comment by begeekmyfriend** [comment]
Well, I think you may pass number 2 in `setEglContextClientVersion()` and have a try.

**Comment by begeekmyfriend** [comment]
Fixed https://github.com/begeekmyfriend/yasea/commit/68cb5a37d17f452361ecb966927d6d5e107ee567
