### ISSUE TITLE
EGL_BAD_CONFIG error

### ISSUE THREAD

**Issue by lzx1** [begeekmyfriend/yasea#207]
yasea2.2运行在小米3和华为某机型上的时候报createContext failed: EGL_BAD_CONFIG错并且出现黑屏现象。

**Comment by begeekmyfriend** [comment]
你把`setEGLContextClientVersion()`参数改成2试试

**Comment by lzx1** [comment]
ok  3q

**Comment by lzx1** [comment]
讲参数改成2之后小米3不会出现createContext failed: EGL_BAD_CONFIG这个错误，但是会出现黑屏现象，然后抛出这个错：
 java.lang.RuntimeException: setParameters failed
                                                                     at android.hardware.Camera.native_setParameters(Native Method)
                                                                     at android.hardware.Camera.setParameters(Camera.java:1671)
                                                                     at net.ossrs.yasea.SrsCameraView.startCamera(SrsCameraView.java:254)
                                                                     at net.ossrs.yasea.SrsPublisher.startEncode(SrsPublisher.java:72)
                                                                     at net.ossrs.yasea.SrsPublisher.startPublish(SrsPublisher.java:104)
                                                                     at net.ossrs.yasea.MainActivity$1.onClick(MainActivity.java:76)
                                                                     at android.view.View.performClick(View.java:4444)
                                                                     at android.view.View$PerformClick.run(View.java:18440)
                                                                     at android.os.Handler.handleCallback(Handler.java:733)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:136)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5016)
                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
                                                                     at dalvik.system.NativeStart.main(Native Method)。

**Comment by begeekmyfriend** [comment]
Comment out this [statement](https://github.com/begeekmyfriend/yasea/blob/gpuimage/app/src/main/java/net/ossrs/yasea/SrsCameraView.java#L264)

**Comment by begeekmyfriend** [comment]
Fixed https://github.com/begeekmyfriend/yasea/commit/715cef59deb87d4e57e60c186762f6b208693530
