### ISSUE TITLE
Error "cannot locate symbol "stpcpy" referenced by "libenc.so""

### ISSUE THREAD

**Issue by rzhepish** [begeekmyfriend/yasea#234]
On Lenovo p780, MTK6589. ARM-v7a appears error while starting application.
Application crashes instantly during launch. Error message below:

`11-18 17:20:12.770 18852-18852/net.ossrs.yasea.demo W/dalvikvm: threadid=1: calling UncaughtExceptionHandler
11-18 17:20:12.771 18852-18852/net.ossrs.yasea.demo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: net.ossrs.yasea.demo, PID: 18852
                                                                      java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "stpcpy" referenced by "libenc.so"...
                                                                          at java.lang.Runtime.loadLibrary(Runtime.java:371)
                                                                          at java.lang.System.loadLibrary(System.java:526)
                                                                          at net.ossrs.yasea.SrsEncoder.<clinit>(SrsEncoder.java:540)
                                                                          at net.ossrs.yasea.SrsPublisher.<init>(SrsPublisher.java:34)
                                                                          at net.ossrs.yasea.demo.MainActivity.onCreate(MainActivity.java:69)
                                                                          at android.app.Activity.performCreate(Activity.java:5277)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2322)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2410)
                                                                          at android.app.ActivityThread.access$800(ActivityThread.java:155)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1331)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                          at android.os.Looper.loop(Looper.java:193)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5395)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:837)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:653)
                                                                          at dalvik.system.NativeStart.main(Native Method)
`

**Comment by spurd0** [comment]
Have same problem, what is your building config & android ver on Lenovo p780?

**Comment by begeekmyfriend** [comment]
Lenovo? Try x86 please. The scripts have been provided.

**Comment by begeekmyfriend** [comment]
Now x86 jniLibs are provided.

**Comment by begeekmyfriend** [comment]
I have found the reason that it is the [libc header compatibility](http://stackoverflow.com/questions/29509779/unsatisfiedlinkerror-when-compiling-with-api21) between API 21 and earlier platform.
