### ISSUE TITLE
couldn't find "libyuv.so"

### ISSUE THREAD

**Issue by farisjameel** [begeekmyfriend/yasea#236]
yasea library is working fine but I am getting this error on Huawei phone

```
E/AndroidRuntime: FATAL EXCEPTION: main
 Process: com.ufan8.app.ufan8, PID: 3937
  java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.ufan8.app.ufan8-1/base.apk"],nativeLibraryDirectories=[/data/app/com.ufan8.app.ufan8-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libyuv.so"
 at java.lang.Runtime.loadLibrary(Runtime.java:378)
 at java.lang.System.loadLibrary(System.java:998)
 at net.ossrs.yasea.SrsEncoder.<clinit>(SrsEncoder.java:549)
at net.ossrs.yasea.SrsPublisher.<init>(SrsPublisher.java:33)
 at com.ufan8.app.ufan8.LiveStreamActivity.onCreate(LiveStreamActivity.java:74)
at android.app.Activity.performCreate(Activity.java:6013)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2359)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466)
at android.app.ActivityThread.access$1200(ActivityThread.java:152)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1341)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:135)
 at android.app.ActivityThread.main(ActivityThread.java:5538)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by farisjameel** [comment]
solved this issue: [reference](https://medium.com/mobiwise-blog/unsatisfiedlinkerror-problem-on-some-android-devices-b77f2f83837d#.roolc64ii)

**Comment by begeekmyfriend** [comment]
All right thank you for your enlightenment https://github.com/begeekmyfriend/yasea/commit/7fd1daac22f045140a48708b0ca9b841f54bfcc9

**Comment by aderinto05** [comment]
I still get issue even follow this https://medium.com/mobiwise-blog/unsatisfiedlinkerror-problem-on-some-android-devices-b77f2f83837d#.roolc64ii

**Comment by aderinto05** [comment]
if reimport folder cpp, is it solve the problem @begeekmyfriend ?

**Comment by begeekmyfriend** [comment]
I am not familiar with your environment. Maybe you need to change some [path](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/cpp/libenc/libenc.cc#L579)?
