### ISSUE TITLE
Access  denied to RTMP Server with nginx-rtmp

### ISSUE THREAD

**Issue by laalex** [begeekmyfriend/yasea#242]
I get the following message:
```
11-26 21:13:22.529 1728-1756/com.codesilk.eswbase I/SrsFlvMuxer: worker: connecting to RTMP server by url=rtmp://192.168.1.56:1935/live/stream
11-26 21:13:22.529 1728-1756/com.codesilk.eswbase D/RtmpConnection: connect() called. Host: 192.168.1.56, port: 1935, appName: live, publishPath: stream
11-26 21:13:22.529 1728-1756/com.codesilk.eswbase W/System.err:     at com.github.faucamp.simplertmp.io.RtmpConnection.connect(RtmpConnection.java:125)
11-26 21:13:22.529 1728-1756/com.codesilk.eswbase W/System.err:     at com.github.faucamp.simplertmp.DefaultRtmpPublisher.connect(DefaultRtmpPublisher.java:23)
11-26 21:13:22.539 1728-1728/com.codesilk.eswbase D/RTMP: RTMP io exception
11-26 21:13:22.539 1728-1728/com.codesilk.eswbase D/RTMP: socket failed: EACCES (Permission denied)
```

I can connect with other streaming clients to the nginx-rtmp configured server and it's working nice. I don't have any auth feature on the server so I don't understand why this is not working.

Best regards,
Alex

**Comment by laalex** [comment]
Sorry, it was an error from my side. I had to do the following: move <uses-permission> outside the <application> tag
