### ISSUE TITLE
HTC crash

### ISSUE THREAD

**Issue by KyrychenkoOleksandr** [begeekmyfriend/yasea#250]
I got the following exception on HTC Desire 320. I used x86 libs that you recently provided.
> Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "stpcpy" referenced by "libenc.so"...
       at java.lang.Runtime.loadLibrary(Runtime.java:371)
       at java.lang.System.loadLibrary(System.java:606)
       at net.ossrs.yasea.SrsEncoder.<clinit>(SrsEncoder.java:540)
       at net.ossrs.yasea.SrsPublisher.<init>(SrsPublisher.java:36)
       at com.live.stream.ProduceStreamActivity.onCreate(ProduceStreamActivity.java:91)
       at android.app.Activity.performCreate(Activity.java:5343)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2331)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2429)
       at android.app.ActivityThread.access$800(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1342)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5333)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by begeekmyfriend** [comment]
Sadly hearing about this... It seems the `jniLibs/x86` I have provided does not work. I think you have to try build x86 by yourself. The building scripts are available.

**Comment by begeekmyfriend** [comment]
Say it again, I do not think it worth spending time on it.

**Comment by begeekmyfriend** [comment]
By the way, I think you need to check the NDK android platform version to see if there is conflict with other application.

**Comment by begeekmyfriend** [comment]
See #270
