### ISSUE TITLE
Crash on the mobile which cpu is armeabi-v7a

### ISSUE THREAD

**Issue by shyhaha** [begeekmyfriend/yasea#253]
Hello, I get the RuntimeExepction on HuaWei and Coolpad mobile which Cpu is armeabi-v7a, but it can work on my ipad which Cpu is  x86, it seems the jniLibs/x86 is ok, but the jniLib/armeabi-v7a is incompatible with the mobile which Cpu is armeabi-v7a.

  java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "stpcpy" referenced by "libenc.so"...
                                                       at java.lang.Runtime.loadLibrary(Runtime.java:364)
                                                       at java.lang.System.loadLibrary(System.java:526)
                                                       at net.ossrs.yasea.SrsEncoder.<clinit>(SrsEncoder.java:540)
                                                       at net.ossrs.yasea.SrsPublisher.<init>(SrsPublisher.java:33)
                                                       at net.ossrs.yasea.demo.MainActivity.onCreate(MainActivity.java:69)
                                                       at android.app.Activity.performCreate(Activity.java:5266)

**Comment by begeekmyfriend** [comment]
See #155 Please check the Android NDK platform version and rebuild it.

**Comment by begeekmyfriend** [comment]
I changed the NDK platform into API 19 and I think that it can work now https://github.com/begeekmyfriend/yasea/commit/6cff148e3f47a3e074d95580191a25aa2ddcdc3a.
