### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "stpcpy" referenced by "libenc.so"

### ISSUE THREAD

**Issue by jutikorn** [begeekmyfriend/yasea#270]
`FATAL EXCEPTION: main
                                                                      Process: net.ossrs.yasea.demo, PID: 28786
                                                                      java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "stpcpy" referenced by "libenc.so"...
                                                                          at java.lang.Runtime.loadLibrary(Runtime.java:365)
                                                                          at java.lang.System.loadLibrary(System.java:526)
                                                                          at net.ossrs.yasea.SrsEncoder.<clinit>(SrsEncoder.java:540)
                                                                          at net.ossrs.yasea.SrsPublisher.<init>(SrsPublisher.java:33)
                                                                          at net.ossrs.yasea.demo.MainActivity.onCreate(MainActivity.java:69)
                                                                          at android.app.Activity.performCreate(Activity.java:5541)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2368)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2464)
                                                                          at android.app.ActivityThread.access$900(ActivityThread.java:172)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:146)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5653)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
                                                                          at dalvik.system.NativeStart.main(Native Method)`

happened on Samsung SM-G7102 firmware 4.4.2 CPU ARM Cortex-A7

**Comment by begeekmyfriend** [comment]
It is the [libc header compatibility](http://stackoverflow.com/questions/29509779/unsatisfiedlinkerror-when-compiling-with-api21) between API 21 and earlier platform.

You may try API 19 NDK platform for earlier machine.

**Comment by jutikorn** [comment]
@begeekmyfriend I tried to rebuild myself with NDK and found 
```
 fatal error: 'x264_config.h' file not found
#include "x264_config.h"
```

**Comment by begeekmyfriend** [comment]
Sadly. Clone it again.

**Comment by jutikorn** [comment]
@begeekmyfriend just tried, still not working. It reflect me the same error:
`jni/libx264/x264.h:46:10: fatal error: 'x264_config.h' file not found
#include "x264_config.h"
`

**Comment by jutikorn** [comment]
I checked out there for the x264_config.h myself and put it in the project and change Platform to 19 then another error show:
`armeabi-v7a/libx264.a(ratecontrol.o):ratecontrol.c:function x264_ratecontrol_new: error: undefined reference to 'stpcpy'`

**Comment by begeekmyfriend** [comment]
It never happens to me just modifying this [line](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/libenc/jni/libx264/android_build_armeabi_v7a.sh#L4)

**Comment by jutikorn** [comment]
@begeekmyfriend hello again,
I tried again by keep **APP_PLATFORM** in Application.mk as android-21 change that [line](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/libenc/jni/libx264/android_build_armeabi_v7a.sh#L4)  which you suggest from **android-21** to **android-19** and re-build. 
Everything seemed to be fine and then I again received the same error that 
`java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "stpcpy" referenced by "libenc.so"...`

Here is my x264_config.h which I told above that it missing:

`#define X264_BIT_DEPTH     8
#define X264_GPL           1
#define X264_INTERLACED    1
#define X264_CHROMA_FORMAT 0
#define X264_VERSION " r2189 35cf912"
#define X264_POINTVER "0.123.2189 35cf912"`

**Comment by begeekmyfriend** [comment]
Why did not keep NDK module all in the same platform??

**Comment by jutikorn** [comment]
@begeekmyfriend If I change APP_PLATFORM := android-19 in Application.mk, it will show me an error says `armeabi-v7a/libx264.a(ratecontrol.o):ratecontrol.c:function x264_ratecontrol_new: error: undefined reference to 'stpcpy'`

**Comment by begeekmyfriend** [comment]
It still does not happen to me. try remove `arm64-v8a` in [Application.mk](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/libenc/jni/Application.mk)

**Comment by jutikorn** [comment]
Still not working when arm64-v8a got removed.

**Comment by begeekmyfriend** [comment]
I changed the NDK platform into API 19 and I think that it can work now.

**Comment by Faiyyaz** [comment]
Hey,

I am using this library in flutter app i am also getting the same issue in Redmi 4A and Samsung M40
