### ISSUE TITLE
貌似有个BUG

### ISSUE THREAD

**Issue by asaupup** [begeekmyfriend/yasea#281]
···
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: net.ossrs.yasea.demo, PID: 15790
                  java.lang.NullPointerException: Attempt to invoke virtual method 'int android.media.MediaFormat.getInteger(java.lang.String)' on a null object reference
                      at net.ossrs.yasea.SrsMp4Muxer$Track.<init>(SrsMp4Muxer.java:533)
                      at net.ossrs.yasea.SrsMp4Muxer$Mp4Movie.addTrack(SrsMp4Muxer.java:684)
                      at net.ossrs.yasea.SrsMp4Muxer.record(SrsMp4Muxer.java:123)
                      at net.ossrs.yasea.SrsPublisher.startRecord(SrsPublisher.java:126)
                      at net.ossrs.yasea.demo.MainActivity$3.onClick(MainActivity.java:119)
                      at android.view.View.performClick(View.java:4909)
                      at android.view.View$PerformClick.run(View.java:20390)
                      at android.os.Handler.handleCallback(Handler.java:815)
                      at android.os.Handler.dispatchMessage(Handler.java:104)
···

**Comment by asaupup** [comment]
srsMp4Muxer没有初始化，而且我没有找到在哪里设置这个参数

**Comment by asaupup** [comment]
startRecord()的时候的错误，demo中直接点RECORD也是这个错误

**Comment by begeekmyfriend** [comment]
Did you call `setRecordHandler` in 'onCreate' function?

**Comment by asaupup** [comment]
调用`setRecordHandler(this)`了，好像，如果不推流，直接录制的话就会出现这个错误

**Comment by begeekmyfriend** [comment]
Fixed https://github.com/begeekmyfriend/yasea/commit/ad73ed43979fa3e20e7156cf5128f635aa0467d0 Thank you!
