### ISSUE TITLE
Landscape mode getting crash 

### ISSUE THREAD

**Issue by nikhilkilivayil** [begeekmyfriend/yasea#297]
FATAL EXCEPTION: main
                                                                      Process: net.ossrs.yasea.demo, PID: 17375
                                                                      java.lang.AssertionError: MTK encoding revolution stride must be 32x
                                                                          at net.ossrs.yasea.SrsEncoder.setScreenOrientation(SrsEncoder.java:289)
                                                                          at net.ossrs.yasea.SrsPublisher.setScreenOrientation(SrsPublisher.java:190)
                                                                          at net.ossrs.yasea.demo.MainActivity.onConfigurationChanged(MainActivity.java:243)
                                                                          at android.app.ActivityThread.performConfigurationChanged(ActivityThread.java:4445)
                                                                          at android.app.ActivityThread.handleConfigurationChanged(ActivityThread.java:4530)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1624)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                          at android.os.Looper.loop(Looper.java:207)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5778)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1015)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)

**Comment by begeekmyfriend** [comment]
Try to comment out these [code](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsEncoder.java#L100-L104).

**Comment by nikhilkilivayil** [comment]
I put 16 in the place of 32. Now it's working. Is that ok?

**Comment by begeekmyfriend** [comment]
As you like. Some MTK chips behave really strange.

**Comment by nikhilkilivayil** [comment]
Ok. Thanks
