### ISSUE TITLE
How to start camera preview on activity start or Before broadcasting start?

### ISSUE THREAD

**Issue by jamariya** [begeekmyfriend/yasea#314]
Hello,

How to start camera preview on activity start? I have read other issue about starting the camera preview on activity start but it doesn't working. I have tried to add following code in SrsCameraView but it's not working.

    public void setPreviewCallback(PreviewCallback cb) {
        mPrevCb = cb;
        getHolder().addCallback(this);
    }

and here is the main activity code:

mPublisher = new SrsPublisher((SrsCameraView) findViewById(R.id.glsurfaceview_camera));
        mPublisher.setEncodeHandler(new SrsEncodeHandler(this));
        mPublisher.setRtmpHandler(new RtmpHandler(this));
        mPublisher.setRecordHandler(new SrsRecordHandler(this));
        mPublisher.setPreviewResolution(1280, 720);

Can you please help?

Thanks in advance.

**Comment by begeekmyfriend** [comment]
Take these [code](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/yasea/demo/MainActivity.java#L85-L87) out and put into `onCreate` method.

**Comment by jamariya** [comment]
Hello Thank you for your reply.

Yes, that's correct. But after implementing these code into onCreate it will start the broadcasting on activity startup. 

I want to start camera preview on activity start so that before starting the broadcasting stream, the camera preview display in background.

Thanks.

**Comment by begeekmyfriend** [comment]
I have separated publishing and camera preview. Please upgrade your source to https://github.com/begeekmyfriend/yasea/commit/4c57223703ce63381ff51e5457ea6f89877ed5c3 and move this [line](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/yasea/demo/MainActivity.java#L87) of code.

**Comment by ngochuu90** [comment]
@jamariya: Have you started camera preview before broadcasting start? 
I do not understand what @begeekmyfriend said

**Comment by begeekmyfriend** [comment]
@ngochuu90 Sorry that the code has been updated so that the line is not in the right position. Just move `mPublisher.startCamera` into `onCreate` method.

**Comment by ngochuu90** [comment]
@begeekmyfriend: When I move `mPublisher.startCamera` in to `onCreate ` method, App crash

This is Error Log:
`E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: net.ossrs.yasea.demo, PID: 21206
                                                                      java.lang.RuntimeException: unknown msg 2
                                                                          at net.ossrs.yasea.SrsEncodeHandler.handleMessage(SrsEncodeHandler.java:53)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                          at android.os.Looper.loop(Looper.java:194)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)`

It seems I must move `mPublisher.startEncode()` above `mPublisher.startCamera()`. And remove `startEndcode` in `mPublisher.startPublish`

**Comment by begeekmyfriend** [comment]
@ngochuu90 Sorry for my mistake. The camera and encoding were not decoupled. Please try this commit. https://github.com/begeekmyfriend/yasea/commit/9f5673a0d8e20a0013c674814cca4d98cce21e54
