### ISSUE TITLE
Fatal exceptions drops the app

### ISSUE THREAD

**Issue by AnastasiyaGolovneva** [begeekmyfriend/yasea#319]
Hello,
I have several fatal exception which dropped the app, while I tried to pass video stream to server. It seems like everything is ok for two-three seconds and then exception is occured. 

`E/AndroidRuntime: FATAL EXCEPTION: Thread-5280
                                     java.lang.IllegalStateException
                                         at android.media.MediaCodec.queueInputBuffer(Native Method)
                                         at net.ossrs.yasea.SrsEncoder.onGetPcmFrame(SrsEncoder.java:353)
                                         at net.ossrs.yasea.SrsPublisher.startAudio(SrsPublisher.java:230)
                                         at net.ossrs.yasea.SrsPublisher.access$300(SrsPublisher.java:17)
                                         at net.ossrs.yasea.SrsPublisher$2.run(SrsPublisher.java:97)

OR

 java.lang.IllegalStateException
                                         at android.media.MediaCodec.dequeueOutputBuffer(Native Method)
                                         at net.ossrs.yasea.SrsEncoder.onGetPcmFrame(SrsEncoder.java:357)
                                         at net.ossrs.yasea.SrsPublisher.startAudio(SrsPublisher.java:230)
                                         at net.ossrs.yasea.SrsPublisher.access$300(SrsPublisher.java:17)
                                         at net.ossrs.yasea.SrsPublisher$2.run(SrsPublisher.java:97)
                                         at java.lang.Thread.run(Thread.java:841)

OR

 FATAL EXCEPTION: Thread-7408
                                     java.lang.IllegalStateException
                                         at android.media.MediaCodec.getBuffers(Native Method)
                                         at android.media.MediaCodec.getInputBuffers(MediaCodec.java:542)
                                         at net.ossrs.yasea.SrsEncoder.onProcessedYuvFrame(SrsEncoder.java:469)
                                         at net.ossrs.yasea.SrsEncoder.onGetRgbaFrame(SrsEncoder.java:162)
                                         at net.ossrs.yasea.SrsPublisher$1.onGetRgbaFrame(SrsPublisher.java:37)
                                         at net.ossrs.yasea.SrsCameraView$4.run(SrsCameraView.java:229)
                                         at java.lang.Thread.run(Thread.java:841)`

Could you say what has caused this behavior or how can I fix this? Or maybe just direction to exlore? 
Thanks

**Comment by begeekmyfriend** [comment]
Code modified or original?

**Comment by AnastasiyaGolovneva** [comment]
Library is original, usage (of library) is just copy-paste from your example

**Comment by begeekmyfriend** [comment]
It seems there is bug in Android encoder NDK. What is your phone?

**Comment by AnastasiyaGolovneva** [comment]
I tested on different models: LG K3 LTE and Asus zenfone 4. There are exceptions in both cases.

**Comment by begeekmyfriend** [comment]
Strange, does the clone of the repository work?

**Comment by AnastasiyaGolovneva** [comment]
From time to time. In general it works, but rarely falls, I can not find reason.

**Comment by begeekmyfriend** [comment]
I suspect the quality of your phone...
