### ISSUE TITLE
libenc.so "has text relocations" issue

### ISSUE THREAD

**Issue by about-prog** [begeekmyfriend/yasea#348]
Hi!
My project uses targetSDKVersion 25. But yasea code gives this error:

```
E/linker: /data/app/net.ossrs.yasea.demo-2/lib/x86/libenc.so: has text relocations
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: net.ossrs.yasea.demo, PID: 4407
                  java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/net.ossrs.yasea.demo-2/lib/x86/libenc.so: has text relocations
                      at java.lang.Runtime.loadLibrary0(Runtime.java:989)
                      at java.lang.System.loadLibrary(System.java:1530)
                      at net.ossrs.yasea.SrsEncoder.<clinit>(SrsEncoder.java:508)
                      at net.ossrs.yasea.SrsPublisher.setEncodeHandler(SrsPublisher.java:281)
                      at net.ossrs.yasea.demo.MainActivity.onCreate(MainActivity.java:71)
                      at android.app.Activity.performCreate(Activity.java:6679)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                      at android.app.ActivityThread.-wrap12(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

I could run my code with yasea only by changing targetSDKVersion to 22.

Is there a way to make yasea work with API 25?

**Comment by begeekmyfriend** [comment]
The so files are built by NDK on level 19 for compatibility. You may resolve it by rebuilding them on higher level.
