### ISSUE TITLE
AndroidRuntime error

### ISSUE THREAD

**Issue by libill** [begeekmyfriend/yasea#353]
02-24 16:05:20.529 28781-28890/net.ossrs.yasea.demo E/AndroidRuntime: FATAL EXCEPTION: Thread-2521
                                                                      Process: net.ossrs.yasea.demo, PID: 28781
                                                                      java.lang.IllegalArgumentException: Unknown message type byte: 8F
                                                                          at com.github.faucamp.simplertmp.packets.RtmpHeader$MessageType.valueOf(RtmpHeader.java:162)
                                                                          at com.github.faucamp.simplertmp.packets.RtmpHeader.readHeaderImpl(RtmpHeader.java:246)
                                                                          at com.github.faucamp.simplertmp.packets.RtmpHeader.readHeader(RtmpHeader.java:225)
                                                                          at com.github.faucamp.simplertmp.io.RtmpDecoder.readPacket(RtmpDecoder.java:36)
                                                                          at com.github.faucamp.simplertmp.io.RtmpConnection.handleRxPacketLoop(RtmpConnection.java:511)
                                                                          at com.github.faucamp.simplertmp.io.RtmpConnection.access$000(RtmpConnection.java:44)
                                                                          at com.github.faucamp.simplertmp.io.RtmpConnection$1.run(RtmpConnection.java:144)
                                                                          at java.lang.Thread.run(Thread.java:818)

**Comment by begeekmyfriend** [comment]
I am afraid it is the wrong format of your RTMP url that make the crash.
