### ISSUE TITLE
Crash while stop publishing

### ISSUE THREAD

**Issue by jake22599** [begeekmyfriend/yasea#366]
I tried integrating the sample codes to my cocos2dx application.
It keep crashing at SrsFlvMuxer. Its pretty weird.

```
03-10 11:25:58.214 24200-24552/{xxxxxx} E/AndroidRuntime: FATAL EXCEPTION: Thread-2413
                                                                         Process: {xxxxxxxxxxx}, PID: 24200
                                                                         java.lang.NullPointerException
                                                                             at net.ossrs.yasea.SrsFlvMuxer$1.run(SrsFlvMuxer.java:168)
                                                                             at java.lang.Thread.run(Thread.java:841)
03-10 11:25:58.224 989-1512/? E/ActivityManagerServiceEx: ** ERROR: PROCESS CRASHED
03-10 11:25:58.224 989-1512/? E/ActivityManagerServiceEx: processName: {xxxxxxxx}
03-10 11:25:58.224 989-1512/? E/ActivityManagerServiceEx: processPid: 24200
03-10 11:25:58.224 989-1512/? E/ActivityManagerServiceEx: shortMsg: java.lang.NullPointerException
03-10 11:25:58.224 989-1512/? E/ActivityManagerServiceEx: longMsg: java.lang.NullPointerException
03-10 11:25:58.224 989-1512/? E/ActivityManagerServiceEx: timeMillis: 1489116358232
03-10 11:25:58.224 989-1512/? E/ActivityManagerServiceEx: stack:
03-10 11:25:58.224 989-1512/? E/ActivityManagerServiceEx: java.lang.NullPointerException
                                                              at net.ossrs.yasea.SrsFlvMuxer$1.run(SrsFlvMuxer.java:168)
                                                              at java.lang.Thread.run(Thread.java:841)
03-10 11:25:58.224 989-1512/? E/ActivityManagerServiceEx: #
```

**Comment by jake22599** [comment]
I found the issue. The crash happened when i attempt to start publish twice without stopping the previous.
