### ISSUE TITLE
At first was onNetworkWeak more time then it was called onNetworkResume and  throw exception and stop stream. What can be wrong?

### ISSUE THREAD

**Issue by bently93** [begeekmyfriend/yasea#376]
```03-21 12:08:36.259 4666-4666/ D/CCTVCamera camera first: onNetworkWeak: 
03-21 12:08:36.299 4666-4666/ D/CCTVCamera camera first: onNetworkWeak: 
03-21 12:08:36.339 4666-4666/ D/CCTVCamera camera first: onNetworkWeak: 
03-21 12:08:36.379 4666-4666/ D/CCTVCamera camera first: onNetworkWeak: 
03-21 12:08:36.419 4666-4666/ D/CCTVCamera camera first: onNetworkWeak: 
03-21 12:08:36.459 4666-4666/ D/CCTVCamera camera first: onNetworkWeak: 
03-21 12:08:36.499 4666-4666/ D/CCTVCamera camera first: onNetworkWeak: 
03-21 12:08:36.539 4666-4666/ D/CCTVCamera camera first: onNetworkWeak: 
03-21 12:08:36.579 4666-4666/ D/CCTVCamera camera first: onNetworkWeak: 
03-21 12:08:36.619 4666-4666/ D/CCTVCamera camera first: onNetworkWeak: 
03-21 12:08:36.649 4666-4666/ I/CCTVCamera camera first: Output Fps: 0,199369
03-21 12:08:36.649 4666-4666/ I/CCTVCamera camera first: Video bitrate: 4,485130 kbps
03-21 12:08:36.709 4666-4666/ D/CCTVCamera camera first: onNetworkResume: 
03-21 12:08:39.169 4666-4666/ E/CCTVCamera camera first: handleException: 
                                                                              java.net.SocketException: sendto failed: EPIPE (Broken pipe)
                                                                                  at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:499)
                                                                                  at libcore.io.IoBridge.sendto(IoBridge.java:468)
                                                                                  at java.net.PlainSocketImpl.write(PlainSocketImpl.java:507)
                                                                                  at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:46)
                                                                                  at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:269)
                                                                                  at java.io.BufferedOutputStream.flushInternal(BufferedOutputStream.java:185)
                                                                                  at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:85)
                                                                                  at com.github.faucamp.simplertmp.io.RtmpConnection.sendRtmpPacket(RtmpConnection.java:497)
                                                                                  at com.github.faucamp.simplertmp.io.RtmpConnection.publishVideoData(RtmpConnection.java:448)
                                                                                  at com.github.faucamp.simplertmp.DefaultRtmpPublisher.publishVideoData(DefaultRtmpPublisher.java:37)
                                                                                  at net.ossrs.yasea.SrsFlvMuxer.sendFlvTag(SrsFlvMuxer.java:146)
                                                                                  at net.ossrs.yasea.SrsFlvMuxer.access$300(SrsFlvMuxer.java:46)
                                                                                  at net.ossrs.yasea.SrsFlvMuxer$1.run(SrsFlvMuxer.java:178)
                                                                                  at java.lang.Thread.run(Thread.java:841)
                                                                               Caused by: libcore.io.ErrnoException: sendto failed: EPIPE (Broken pipe)
                                                                                  at libcore.io.Posix.sendtoBytes(Native Method)
                                                                                  at libcore.io.Posix.sendto(Posix.java:156)
                                                                                  at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:177)
                                                                                  at libcore.io.IoBridge.sendto(IoBridge.java:466)
                                                                                  at java.net.PlainSocketImpl.write(PlainSocketImpl.java:507) 
                                                                                  at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:46) 
                                                                                  at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:269) 
                                                                                  at java.io.BufferedOutputStream.flushInternal(BufferedOutputStream.java:185) 
                                                                                  at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:85) 
                                                                                  at com.github.faucamp.simplertmp.io.RtmpConnection.sendRtmpPacket(RtmpConnection.java:497) 
                                                                                  at com.github.faucamp.simplertmp.io.RtmpConnection.publishVideoData(RtmpConnection.java:448) 
                                                                                  at com.github.faucamp.simplertmp.DefaultRtmpPublisher.publishVideoData(DefaultRtmpPublisher.java:37) 
                                                                                  at net.ossrs.yasea.SrsFlvMuxer.sendFlvTag(SrsFlvMuxer.java:146) 
                                                                                  at net.ossrs.yasea.SrsFlvMuxer.access$300(SrsFlvMuxer.java:46) 
                                                                                  at net.ossrs.yasea.SrsFlvMuxer$1.run(SrsFlvMuxer.java:178) 
                                                                                  at java.lang.Thread.run(Thread.java:841) 
03-21 12:08:39.189 4666-4666/cloud.cityscreen.cctv E/CCTVCamera camera first: handleException: 
                                                                              java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)
                                                                                  at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:545)
                                                                                  at libcore.io.IoBridge.recvfrom(IoBridge.java:509)
                                                                                  at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)
                                                                                  at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
                                                                                  at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:240)
                                                                                  at java.io.InputStream.read(InputStream.java:162)
                                                                                  at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:142)
                                                                                  at java.io.BufferedInputStream.read(BufferedInputStream.java:227)
                                                                                  at com.github.faucamp.simplertmp.packets.RtmpHeader.readHeaderImpl(RtmpHeader.java:231)
                                                                                  at com.github.faucamp.simplertmp.packets.RtmpHeader.readHeader(RtmpHeader.java:225)
                                                                                  at com.github.faucamp.simplertmp.io.RtmpDecoder.readPacket(RtmpDecoder.java:36)
                                                                                  at com.github.faucamp.simplertmp.io.RtmpConnection.handleRxPacketLoop(RtmpConnection.java:517)
                                                                                  at com.github.faucamp.simplertmp.io.RtmpConnection.access$000(RtmpConnection.java:44)
                                                                                  at com.github.faucamp.simplertmp.io.RtmpConnection$1.run(RtmpConnection.java:150)
                                                                                  at java.lang.Thread.run(Thread.java:841)
                                                                               Caused by: libcore.io.ErrnoException: recvfrom failed: ECONNRESET (Connection reset by peer)
                                                                                  at libcore.io.Posix.recvfromBytes(Native Method)
                                                                                  at libcore.io.Posix.recvfrom(Posix.java:141)
                                                                                  at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:164)
                                                                                  at libcore.io.IoBridge.recvfrom(IoBridge.java:506)
                                                                                  at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488) 
                                                                                  at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46) 
                                                                                  at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:240) 
                                                                                  at java.io.InputStream.read(InputStream.java:162) 
                                                                                  at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:142) 
                                                                                  at java.io.BufferedInputStream.read(BufferedInputStream.java:227) 
                                                                                  at com.github.faucamp.simplertmp.packets.RtmpHeader.readHeaderImpl(RtmpHeader.java:231) 
                                                                                  at com.github.faucamp.simplertmp.packets.RtmpHeader.readHeader(RtmpHeader.java:225) 
                                                                                  at com.github.faucamp.simplertmp.io.RtmpDecoder.readPacket(RtmpDecoder.java:36) 
                                                                                  at com.github.faucamp.simplertmp.io.RtmpConnection.handleRxPacketLoop(RtmpConnection.java:517) 
                                                                                  at com.github.faucamp.simplertmp.io.RtmpConnection.access$000(RtmpConnection.java:44) 
                                                                                  at com.github.faucamp.simplertmp.io.RtmpConnection$1.run(RtmpConnection.java:150) 
                                                                                  at java.lang.Thread.run(Thread.java:841) 
```

**Comment by begeekmyfriend** [comment]
Your network environment (the connection to RTMP server) is not good enough.

**Comment by bently93** [comment]
This is understandable. But the fact is that it no longer connects and does not broadcast video

**Comment by begeekmyfriend** [comment]
I am afraid you do not get the permission.
