### ISSUE TITLE
使用硬體解碼會遇到crash

### ISSUE THREAD

**Issue by mabowgithub** [begeekmyfriend/yasea#381]
您好，使用您的範例建置於 API 19 （4.4 ）的裝置上使用硬體解碼會遇到crash。
請問是跟裝置的支援性有相關嗎？  謝謝

FATAL EXCEPTION: Thread-190
                                                 Process: net.ossrs.yasea.demo, PID: 3637
                                                 java.lang.IllegalStateException
                                                     at android.media.MediaCodec.getBuffers(Native Method)
                                                     at android.media.MediaCodec.getInputBuffers(MediaCodec.java:542)
                                                     at net.ossrs.yasea.SrsEncoder.onProcessedYuvFrame(SrsEncoder.java:297)
                                                     at net.ossrs.yasea.SrsEncoder.onGetRgbaFrame(SrsEncoder.java:377)
                                                     at net.ossrs.yasea.SrsPublisher$1.onGetRgbaFrame(SrsPublisher.java:43)
                                                     at net.ossrs.yasea.SrsCameraView$4.run(SrsCameraView.java:229)
                                                     at java.lang.Thread.run(Thread.java:841)

**Comment by begeekmyfriend** [comment]
我不确定你的手机有没有ROM过

**Comment by ChallyCai** [comment]
Rom ?我也遇到这样的问题。ROM 怎么影响这个问题的呢？

**Comment by begeekmyfriend** [comment]
@ChallyCai 就是涉及到native的实现不一致，同SDK不兼容
