### ISSUE TITLE
Demo crashes when trying to connect to the camera

### ISSUE THREAD

**Issue by lfdversluis** [begeekmyfriend/yasea#382]
```
Caused by: java.lang.RuntimeException: Fail to connect to camera service
                                                                                           at android.hardware.Camera.<init>(Camera.java:520)
                                                                                           at android.hardware.Camera.open(Camera.java:361)
                                                                                           at net.ossrs.yasea.SrsCameraView.openCamera(SrsCameraView.java:350)
                                                                                           at net.ossrs.yasea.SrsCameraView.setPreviewResolution(SrsCameraView.java:141)
                                                                                           at net.ossrs.yasea.SrsPublisher.setPreviewResolution(SrsPublisher.java:224)

```

The well known camera cannot open bug. Any fix for this when using the SrsCameraView?

**Comment by lfdversluis** [comment]
Nvm, was an issue on my side.

**Comment by curtis2** [comment]
which is it ?  I can't find it.  Can you get me the issue link? thanks.

**Comment by lfdversluis** [comment]
@curtis2 I forgot to add camera permissions in the manifest for <22 API
