### ISSUE TITLE
use rtmp for publish broadcast

### ISSUE THREAD

**Issue by imamhambali0221** [begeekmyfriend/yasea#384]
i have url rtmp (from back end) to start the broadcast video. when i start the app i just input the url rtmp and click the publish button, the app always force close. i just record the error message in android monitor like this

> 03-26 23:24:52.313 15989-16494/net.ossrs.yasea.demo I/OMXClient: Using client-side OMX mux.
03-26 23:24:52.322 15989-15989/net.ossrs.yasea.demo D/AndroidRuntime: Shutting down VM
03-26 23:24:52.327 15989-15989/net.ossrs.yasea.demo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: net.ossrs.yasea.demo, PID: 15989
                                                                      Theme: themes:{}
                                                                      android.media.MediaCodec$CodecException: Error 0x80000000
                                                                          at android.media.MediaCodec.native_configure(Native Method)
                                                                          at android.media.MediaCodec.configure(MediaCodec.java:1781)
                                                                          at net.ossrs.yasea.SrsEncoder.start(SrsEncoder.java:163)
                                                                          at net.ossrs.yasea.SrsPublisher.startEncode(SrsPublisher.java:143)
                                                                          at net.ossrs.yasea.SrsPublisher.startPublish(SrsPublisher.java:162)
                                                                          at net.ossrs.yasea.demo.MainActivity$1.onClick(MainActivity.java:88)
                                                                          at android.view.View.performClick(View.java:5204)
                                                                          at android.view.View$PerformClick.run(View.java:21159)
                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5475)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

please tell me about that.

thanks advance.

**Comment by begeekmyfriend** [comment]
It seems `CodecException` in custom Android ROM. Would you please tell me the model?

**Comment by imamhambali0221** [comment]
i use custom Andorid ROM build in galaxy tab 2 7.0. i think that is the issue when i use the custom Android ROM. but would you please tell me the solution clearly and what should i do clear that issue. thank you advance. @begeekmyfriend

**Comment by begeekmyfriend** [comment]
I am afraid that is not what we can make in SDK layer...

**Comment by imamhambali0221** [comment]
oke that's clear. but i have some question again if i want to configure the url rtmp with this format (rtmp://server:port/hls) and i have key too. What should i do to modify the library with that format and also the key input. As long as i know the library need appName and streamName. thanks advance. @begeekmyfriend

**Comment by begeekmyfriend** [comment]
In fact you do not need to change anything with the library according to the URL. What is up?

**Comment by imamhambali0221** [comment]
but i still get "Invalid RTMP URL. Must be in format: rtmp://host[:port]/application/streamName". base on the url rtmp from back end only that format. "hls" is application name or stream name?
thanks advance @begeekmyfriend

**Comment by begeekmyfriend** [comment]
I see. HLS is about transcoding on server end and does nothing with streaming end. You can play the [list](https://github.com/google/ExoPlayer/blob/release-v2/demo/src/main/assets/media.exolist.json#L307) by FFplay.

**Comment by imamhambali0221** [comment]
oke, how about the flow sir? would you tell us how about this library's work.? because i don't have the basic of broadcasting flow in android code. thanks advance @begeekmyfriend

**Comment by begeekmyfriend** [comment]
HLS does noting with RTMP as well as streaming. It is the business of server.
