### ISSUE TITLE
Works on one device and not on another -  Fail to connect to camera service

### ISSUE THREAD

**Issue by cagneymoreau** [begeekmyfriend/yasea#387]
I tried my best but I am still learning and cannot seem to resolve this issue.
It woks fine on a samasung note 3 v5.0
But will not open on a kyocera running 5.1.1

I will likely try something else but if anyone knows how to fix this or if this of interest here it is.

`

FATAL EXCEPTION: main
                                                                      Process: net.ossrs.yasea.demo, PID: 26049
                                                                      java.lang.RuntimeException: Unable to start activity ComponentInfo{net.ossrs.yasea.demo/net.ossrs.yasea.demo.MainActivity}: java.lang.RuntimeException: Fail to connect to camera service
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2357)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2447)
                                                                          at android.app.ActivityThread.access$800(ActivityThread.java:163)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1327)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:135)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5438)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
                                                                       Caused by: java.lang.RuntimeException: Fail to connect to camera service
                                                                          at android.hardware.Camera.<init>(Camera.java:600)
                                                                          at android.hardware.Camera.open(Camera.java:420)
                                                                          at net.ossrs.yasea.SrsCameraView.openCamera(SrsCameraView.java:356)
                                                                          at net.ossrs.yasea.SrsCameraView.setPreviewResolution(SrsCameraView.java:144)
                                                                          at net.ossrs.yasea.SrsPublisher.setPreviewResolution(SrsPublisher.java:224)
                                                                          at net.ossrs.yasea.demo.MainActivity.onCreate(MainActivity.java:74)
                                                                          at android.app.Activity.performCreate(Activity.java:6033)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2310)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2447) 
                                                                          at android.app.ActivityThread.access$800(ActivityThread.java:163) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1327) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:135) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5438) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:372) 
`

**Comment by begeekmyfriend** [comment]
I am afraid the Kyocera is not the mainstream Android device with custom ROM.

**Comment by curtis2** [comment]
I have the same mistake.  and my devices is  Lenovo 2 A8-50F,  android version is 5.1.1.   I don't what wrong with it. but I know The camera class is deprecated. Why we still use it?

**Comment by curtis2** [comment]
miui  5 too.

**Comment by begeekmyfriend** [comment]
@curtis2 I guess there are some parameters that do not match the camera service in ROM. You can change some of [them](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsCameraView.java#L273) and try to find out the reason.
