### ISSUE TITLE
java.lang.RuntimeException: setParameters failed

### ISSUE THREAD

**Issue by abhishekcharismatic** [begeekmyfriend/yasea#418]
Sir I have tried your code. Its working fine on some devices but on other hand, it giving error on some devices. This is the error catlog:

java.lang.RuntimeException: Unable to start activity ComponentInfo{net.ossrs.yasea.demo/net.ossrs.yasea.demo.MainActivity}: java.lang.RuntimeException: setParameters failed
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2351)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413)
                                                                          at android.app.ActivityThread.access$800(ActivityThread.java:154)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:135)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5357)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:952)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:747)
                                                                       Caused by: java.lang.RuntimeException: setParameters failed
                                                                          at android.hardware.Camera.native_setParameters(Native Method)
                                                                          at android.hardware.Camera.setParameters(Camera.java:1912)
                                                                          at net.ossrs.yasea.SrsCameraView.startCamera(SrsCameraView.java:306)
                                                                          at net.ossrs.yasea.SrsPublisher.startCamera(SrsPublisher.java:63)
                                                                          at net.ossrs.yasea.demo.MainActivity.onCreate(MainActivity.java:77)
                                                                          at android.app.Activity.performCreate(Activity.java:6031)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2295)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413) 
                                                                          at android.app.ActivityThread.access$800(ActivityThread.java:154) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:135) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5357) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:952) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:747) 
04-28 10:34:33.283 11674-11674/net.ossrs.yasea.demo I/Process: Sending signal. PID: 11674 SIG: 9

Can you please tell me how to fix this issue as it is not supporting camera of some devices.

**Comment by begeekmyfriend** [comment]
Set [preview resolution](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/yasea/demo/MainActivity.java#L74) as 640x480.

**Comment by abhishekcharismatic** [comment]
Thank alot sir.. It works.. And I am facing one more issue.. While testing this application on device 5 inch screen it's working fine. But in 5'5 inch screen or above video gets stretched. How to fix it so that video never get stretched in any device no matter the size of the screen??

**Comment by begeekmyfriend** [comment]
I am afraid there are only 2 ways:
- Change the preview resolution which most fit the screen size;
- Change the display view size so that it fits the preview resolution.

**Comment by abhishekcharismatic** [comment]
Okkk so most fit screen size for all device according to you is?? And the video is little bit zoom out. How to resolve it?? 640x480 worked. But little bit zoom out. and little stretched on device more than 5'5 inch screen.

**Comment by abhishekcharismatic** [comment]
Sir, My Surfaceview is vertically stretched.. How to resolve it issue??
