### ISSUE TITLE
App crash in Version 7.0 while  mCamera.setParameters(params)

### ISSUE THREAD

**Issue by avinash7074** [begeekmyfriend/yasea#438]
Hi ,

When I am calling mPublisher.startCamera(); the application got crash.

The following is crash log.

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.therevolverlife/com.therevolverlife.LiveStreamingNewScreenActivity}: java.lang.RuntimeException: setParameters failed
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2947)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3008)
	at android.app.ActivityThread.-wrap14(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6688)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
Caused by: java.lang.RuntimeException: setParameters failed
	at android.hardware.Camera.native_setParameters(Native Method)
	at android.hardware.Camera.setParameters(Camera.java:1940)
	at net.ossrs.yasea.SrsCameraView.startCamera(SrsCameraView.java:307)
	at net.ossrs.yasea.SrsPublisher.startCamera(SrsPublisher.java:68)
	at com.therevolverlife.LiveStreamingNewScreenActivity.initStream(LiveStreamingNewScreenActivity.java:547)
	at com.therevolverlife.LiveStreamingNewScreenActivity.mDeclaration(LiveStreamingNewScreenActivity.java:176)
	at com.therevolverlife.LiveStreamingNewScreenActivity.onCreate(LiveStreamingNewScreenActivity.java:126)
	at android.app.Activity.performCreate(Activity.java:6912)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2900)
	... 9 more

Thank you.

**Comment by begeekmyfriend** [comment]
Change the [resolution](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/yasea/demo/MainActivity.java#L74) into 640x480

**Comment by avinash7074** [comment]
I am setting the resolution that are getting from getPreviewSize()

**Comment by avinash7074** [comment]
Width and Height selected by user that are getting from getPreviewSize()
mPublisher.setPreviewResolution(Width, Height); 
mPublisher.setOutputResolution(Width, Height); 

I am setting the same width and height. in setPreviewResolution and setOutputResolution.

**Comment by begeekmyfriend** [comment]
What I mean is that your device does not support 640x360 preview resolution but 640x480. And the output resolution does nothing with it.

**Comment by avinash7074** [comment]
Hi,

When i am doing live streaming in portrait the video gets stretch.
Here I am attaching the screenshot of my live streaming.

Please let me know how I can solve this issue.
Thank you.

![livestream1](https://cloud.githubusercontent.com/assets/28567882/26344090/0a6ff9b6-3fbc-11e7-8e98-1aa4a6cd5fbe.png)
![livestream2](https://cloud.githubusercontent.com/assets/28567882/26344091/0a71ea78-3fbc-11e7-8df2-a739e4259e4e.png)
