### ISSUE TITLE
Broadcast stop action getting delay and UI blocks

### ISSUE THREAD

**Issue by nikhilkilivayil** [begeekmyfriend/yasea#446]
In some devices getting UI block while pressing stop button. 
```java
public void stopCamera() {
        if (worker != null) {
            worker.interrupt();
            try {
                worker.join();
                Log.i("worker join","Finished");
            } catch (InterruptedException e) {
                e.printStackTrace();
                worker.interrupt();
            }
        }
}
```
In this code worker.join() method taking 4 or 5 second to work. And UI also blocked. 

After I tried to join with a specific time : worker.join(500). Now it's getting stoped at the same time. But, its crashing some times.

and showing this error:

 java.lang.IllegalStateException: buffer was freed
                                                                               at java.nio.DirectByteBuffer.checkNotFreed(DirectByteBuffer.java:557)
                                                                               at java.nio.DirectByteBuffer.checkIsAccessible(DirectByteBuffer.java:549)
                                                                               at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:170)
                                                                               at net.ossrs.yasea.SrsFlvMuxer$SrsUtils.srs_avc_startswith_annexb(SrsFlvMuxer.java:455)
                                                                               at net.ossrs.yasea.SrsFlvMuxer$SrsRawH264Stream.annexb_demux(SrsFlvMuxer.java:745)
                                                                               at net.ossrs.yasea.SrsFlvMuxer$SrsFlv.writeVideoSample(SrsFlvMuxer.java:945)
                                                                               at net.ossrs.yasea.SrsFlvMuxer.writeSampleData(SrsFlvMuxer.java:233)
                                                                               at net.ossrs.yasea.SrsEncoder.onEncodedAnnexbFrame(SrsEncoder.java:352)
                                                                               at net.ossrs.yasea.SrsEncoder.onProcessedYuvFrame(SrsEncoder.java:331)
                                                                               at net.ossrs.yasea.SrsEncoder.onGetRgbaFrame(SrsEncoder.java:398)
                                                                               at net.ossrs.yasea.SrsPublisher$1.onGetRgbaFrame(SrsPublisher.java:44)
                                                                               at net.ossrs.yasea.SrsCameraView$4.run(SrsCameraView.java:248)
                                                                               at java.lang.Thread.run(Thread.java:818)

**Comment by begeekmyfriend** [comment]
Please clone the latest version first.
