### ISSUE TITLE
有没有arm64-v8a支持so

### ISSUE THREAD

**Issue by wasdzy111** [begeekmyfriend/yasea#483]
能不能给个arm64-v8a的支持so 
wasdzy@sina.com  谢谢

**Comment by begeekmyfriend** [comment]
Add `arm64-v8a` into `APP_ABI` and replace `android-19` with `android-21` in `APP_PLATFORM` in [Application.mk](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/cpp/Application.mk).
Add `arm64-v8a` into [build.gradle](https://github.com/begeekmyfriend/yasea/blob/master/library/build.gradle#L15)

**Comment by wasdzy111** [comment]
I tried on the tips you gave me, but I failed.
Maybe my link is wrong. Can you send a.So file directly to me?
My email:wasdzy@sina.com

**Comment by wasdzy111** [comment]
我按照你的给的方法，但是一直报错，在window下能编译吗？

**Comment by begeekmyfriend** [comment]
Android Studio -> Settings -> System Settings -> Android SDK -> SDK Tools -> NDK

**Comment by wasdzy111** [comment]
这个安装好的

**Comment by wasdzy111** [comment]
Error while executing process D:\Android\sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=C:\Users\BINGO\Desktop\yasea-2.6\yasea-2.6\library\src\main\cpp\Android.mk NDK_APPLICATION_MK=C:\Users\BINGO\Desktop\yasea-2.6\yasea-2.6\library\src\main\cpp\Application.mk APP_ABI=arm64-v8a NDK_ALL_ABIS=arm64-v8a NDK_DEBUG=0 APP_PLATFORM=android-21 NDK_OUT=C:/Users/BINGO/Desktop/yasea-2.6/yasea-2.6/library/build/intermediates/ndkBuild/release/obj NDK_LIBS_OUT=C:\Users\BINGO\Desktop\yasea-2.6\yasea-2.6\library\build\intermediates\ndkBuild\release\lib APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
Android NDK: ERROR:C:/Users/BINGO/Desktop/yasea-2.6/yasea-2.6/library/src/main/cpp/libx264/Android.mk:x264: The LOCAL_SRC_FILES for a prebuilt library should only contain one item

**Comment by begeekmyfriend** [comment]
我昨天不是给你发了`libx264.a`要放到`libs`目录下的吗？

**Comment by wasdzy111** [comment]
非常抱歉，没有收到邮件
能不能上传到github中 我直接下载呢？
或者麻烦你再给122078348@qq.com邮箱发一个

**Comment by begeekmyfriend** [comment]
晕，我是说昨天我回复你如何运行`libx264`目录里的编译脚本……

**Comment by wasdzy111** [comment]
能不能给一个完整的步骤？

**Comment by wasdzy111** [comment]
JNI DETECTED ERROR IN APPLICATION: JNI NewGlobalRef called with pending exception java.lang.NoSuchMethodError: no static or non-static method "Lnet/ossrs/yasea/SrsEncoder;.ARGBToI420Scaled([IIIZIIIII)[B"
07-26 11:49:45.957 26686-26686/com.pactera.emdc.activity.ui E/art:     at java.lang.String java.lang.Runtime.nativeLoad(java.lang.String, java.lang.ClassLoader, java.lang.String) (Runtime.java:-2)
07-26 11:49:45.957 26686-26686/com.pactera.emdc.activity.ui E/art:     at java.lang.String java.lang.Runtime.doLoad(java.lang.String, java.lang.ClassLoader) (Runtime.java:435)
07-26 11:49:45.957 26686-26686/com.pactera.emdc.activity.ui E/art:     at void java.lang.Runtime.loadLibrary(java.lang.String, java.lang.ClassLoader) (Runtime.java:370)
07-26 11:49:45.957 26686-26686/com.pactera.emdc.activity.ui E/art:     at void java.lang.System.loadLibrary(java.lang.String) (System.java:1076)
07-26 11:49:45.957 26686-26686/com.pactera.emdc.activity.ui E/art:     at void net.ossrs.yasea.SrsEncoder.<clinit>() (SrsEncoder.java:506)
07-26 11:49:45.957 26686-26686/com.pactera.emdc.activity.ui E/art:     at void net.ossrs.yasea.SrsPublisher.setEncodeHandler(net.ossrs.yasea.SrsEncodeHandler) (SrsPublisher.java:303)
07-26 11:49:45.957 26686-26686/com.pactera.emdc.activity.ui E/art:     at void com.pactera.emdc.activity.ui.ui.main.view.LiveActivity.onCreate(android.os.Bundle) (LiveActivity.java:54)
07-26 11:49:45.957 26686-26686/com.pactera.emdc.activity.ui E/art:     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6309)
07-26 11:49:45.957 26686-26686/com.pactera.emdc.activity.ui E/art:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1113)
07-26 11:49:45.957 26686-26686/com.pactera.emdc.activity.ui E/art:     at void cn.jiguang.a.a.d.a.a.d.callActivityOnCreate(android.app.Activity, android.os.Bundle) ((null):-1)
07-26 11:49:45.957 26686-26686/com.pactera.emdc.activity.ui E/art:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2519)
07-26 11:49:45.957 26686-26686/com.pactera.emdc.activity.ui E/art:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2654)
07-26 11:49:45.957 26686-26686/com.pactera.emdc.activity.ui E/art:     at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:-1)
07-26 11:49:45.957 26686-26686/com.pactera.emdc.activity.ui E/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1488)
07-26 11:49:45.957 26686-26686/com.pactera.emdc.activity.ui E/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:111)
07-26 11:49:45.957 26686-26686/com.pactera.emdc.activity.ui E/art:     at void android.os.Looper.loop() (Looper.java:207)
07-26 11:49:45.957 26686-26686/com.pactera.emdc.activity.ui E/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:5728)
07-26 11:49:45.957 26686-26686/com.pactera.emdc.activity.ui E/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
07-26 11:49:45.957 26686-26686/com.pactera.emdc.activity.ui E/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:789)
07-26 11:49:45.957 26686-26686/com.pactera.emdc.activity.ui E/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:679)
07-26 11:49:45.957 26686-26686/com.pactera.emdc.activity.ui E/art:     in call to NewGlobalRef
07-26 11:49:45.957 26686-26686/com.pactera.emdc.activity.ui E/art:     from java.lang.String java.lang.Runtime.nativeLoad(java.lang.String, java.lang.ClassLoader, java.lang.String)
07-26 11:49:45.957 26686-26686/com.pactera.emdc.activity.ui E/art: "main" prio=5 tid=1 Runnable
07-26 11:49:45.957 26686-26686/com.pactera.emdc.activity.ui E/art:   | group="main" sCount=0 dsCount=0 obj=0x753f2c78 self=0x7f9213c400
07-26 11:49:45.958 26686-26686/com.pactera.emdc.activity.ui E/art:   | sysTid=26686 nice=0 cgrp=default sched=0/0 handle=0x7f95e032c0
07-26 11:49:45.958 26686-26686/com.pactera.emdc.activity.ui E/art:   | state=R schedstat=( 1615237090 47269376 395 ) utm=138 stm=23 core=2 HZ=100
07-26 11:49:45.958 26686-26686/com.pactera.emdc.activity.ui E/art:   | stack=0x7feb015000-0x7feb017000 stackSize=8MB
07-26 11:49:45.958 26686-26686/com.pactera.emdc.activity.ui E/art:   | held mutexes= "mutator lock"(shared held)
07-26 11:49:45.958 26686-26686/com.pactera.emdc.activity.ui E/art:     at java.lang.Runtime.nativeLoad(Native method)
07-26 11:49:45.958 26686-26686/com.pactera.emdc.activity.ui E/art:     at java.lang.Runtime.doLoad(Runtime.java:435)
07-26 11:49:45.958 26686-26686/com.pactera.emdc.activity.ui E/art:   - locked <0x0dbe264c> (a java.lang.Runtime)
07-26 11:49:45.958 26686-26686/com.pactera.emdc.activity.ui E/art:     at java.lang.Runtime.loadLibrary(Runtime.java:370)
07-26 11:49:45.958 26686-26686/com.pactera.emdc.activity.ui E/art:     at java.lang.System.loadLibrary(System.java:1076)
07-26 11:49:45.958 26686-26686/com.pactera.emdc.activity.ui E/art:     at net.ossrs.yasea.SrsEncoder.<clinit>(SrsEncoder.java:506)
07-26 11:49:45.958 26686-26686/com.pactera.emdc.activity.ui E/art:     at net.ossrs.yasea.SrsPublisher.setEncodeHandler(SrsPublisher.java:303)
07-26 11:49:45.958 26686-26686/com.pactera.emdc.activity.ui E/art:     at com.pactera.emdc.activity.ui.ui.main.view.LiveActivity.onCreate(LiveActivity.java:54)
07-26 11:49:45.958 26686-26686/com.pactera.emdc.activity.ui E/art:     at android.app.Activity.performCreate(Activity.java:6309)
07-26 11:49:45.958 26686-26686/com.pactera.emdc.activity.ui E/art:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
07-26 11:49:45.958 26686-26686/com.pactera.emdc.activity.ui E/art:     at cn.jiguang.a.a.d.a.a.d.callActivityOnCreate(unavailable:-1)
07-26 11:49:45.958 26686-26686/com.pactera.emdc.activity.ui E/art:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2519)
07-26 11:49:45.958 26686-26686/com.pactera.emdc.activity.ui E/art:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2654)
07-26 11:49:45.958 26686-26686/com.pactera.emdc.activity.ui E/art:     at android.app.ActivityThread.-wrap11(ActivityThread.java:-1)
07-26 11:49:45.958 26686-26686/com.pactera.emdc.activity.ui E/art:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488)
07-26 11:49:45.958 26686-26686/com.pactera.emdc.activity.ui E/art:     at android.os.Handler.dispatchMessage(Handler.java:111)
07-26 11:49:45.958 26686-26686/com.pactera.emdc.activity.ui E/art:     at android.os.Looper.loop(Looper.java:207)
07-26 11:49:45.958 26686-26686/com.pactera.emdc.activity.ui E/art:     at android.app.ActivityThread.main(ActivityThread.java:5728)
07-26 11:49:45.958 26686-26686/com.pactera.emdc.activity.ui E/art:     at java.lang.reflect.Method.invoke!(Native method)
07-26 11:49:45.958 26686-26686/com.pactera.emdc.activity.ui E/art:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
07-26 11:49:45.958 26686-26686/com.pactera.emdc.activity.ui E/art:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

**Comment by wasdzy111** [comment]
JNI DETECTED ERROR IN APPLICATION: JNI NewGlobalRef called with pending exception java.lang.NoSuchMethodError: no static or non-static method "Lnet/ossrs/yasea/SrsEncoder;.ARGBToI420Scaled([IIIZIIIII)[B"
     at java.lang.String java.lang.Runtime.nativeLoad(java.lang.String, java.lang.ClassLoader, java.lang.String) (Runtime.java:-2)
     at java.lang.String java.lang.Runtime.doLoad(java.lang.String, java.lang.ClassLoader) (Runtime.java:435)
     at void java.lang.Runtime.loadLibrary(java.lang.String, java.lang.ClassLoader) (Runtime.java:370)
     at void java.lang.System.loadLibrary(java.lang.String) (System.java:1076)
     at void net.ossrs.yasea.SrsEncoder.<clinit>() (SrsEncoder.java:506)
     at void net.ossrs.yasea.SrsPublisher.setEncodeHandler(net.ossrs.yasea.SrsEncodeHandler) (SrsPublisher.java:303)
     at void com.pactera.emdc.activity.ui.ui.main.view.LiveActivity.onCreate(android.os.Bundle) (LiveActivity.java:54)
     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6309)
     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1113)
     at void cn.jiguang.a.a.d.a.a.d.callActivityOnCreate(android.app.Activity, android.os.Bundle) ((null):-1)
     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2519)
     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2654)
     at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:-1)
     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1488)
     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:111)
     at void android.os.Looper.loop() (Looper.java:207)
     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:5728)
     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:789)
     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:679)
     in call to NewGlobalRef
     from java.lang.String java.lang.Runtime.nativeLoad(java.lang.String, java.lang.ClassLoader, java.lang.String)
 "main" prio=5 tid=1 Runnable
   | group="main" sCount=0 dsCount=0 obj=0x753f2c78 self=0x7f9213c400
   | sysTid=26686 nice=0 cgrp=default sched=0/0 handle=0x7f95e032c0
   | state=R schedstat=( 1615237090 47269376 395 ) utm=138 stm=23 core=2 HZ=100
   | stack=0x7feb015000-0x7feb017000 stackSize=8MB
   | held mutexes= "mutator lock"(shared held)
     at java.lang.Runtime.nativeLoad(Native method)
     at java.lang.Runtime.doLoad(Runtime.java:435)
   - locked <0x0dbe264c> (a java.lang.Runtime)
     at java.lang.Runtime.loadLibrary(Runtime.java:370)
     at java.lang.System.loadLibrary(System.java:1076)
     at net.ossrs.yasea.SrsEncoder.<clinit>(SrsEncoder.java:506)
     at net.ossrs.yasea.SrsPublisher.setEncodeHandler(SrsPublisher.java:303)
     at com.pactera.emdc.activity.ui.ui.main.view.LiveActivity.onCreate(LiveActivity.java:54)
     at android.app.Activity.performCreate(Activity.java:6309)
     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
     at cn.jiguang.a.a.d.a.a.d.callActivityOnCreate(unavailable:-1)
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2519)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2654)
     at android.app.ActivityThread.-wrap11(ActivityThread.java:-1)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488)
     at android.os.Handler.dispatchMessage(Handler.java:111)
     at android.os.Looper.loop(Looper.java:207)
     at android.app.ActivityThread.main(ActivityThread.java:5728)
     at java.lang.reflect.Method.invoke!(Native method)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
