### ISSUE TITLE
Invalid EXT-X-TARGETDURATION for first fragment in HLS stream

### ISSUE THREAD

**Issue by shwetanks** [begeekmyfriend/yasea#493]
I am observing an invalid target-duration for first fragment when publishing to a nginx-rtmp server using SrsPublisher#startPublish
Following is a .m3u8 file generated in the process and some logs from nginx-rtmp module are also attached (please notice the large value 204963823041217)

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TARGETDURATION:204963823041217
#EXTINF:204963823041217.156,
894888126341857280-0.ts
#EXTINF:2.151,
894888126341857280-1.ts
#EXTINF:2.109,
894888126341857280-2.ts
#EXTINF:2.150,
894888126341857280-3.ts
#EXTINF:2.141,
894888126341857280-4.ts
#EXTINF:2.154,
...

attached - detailed debug of nginx-rtmp from publish start to first fragment write

[invalid_first_frame_duration.txt](https://github.com/begeekmyfriend/yasea/files/1210474/invalid_first_frame_duration.txt)

what could it be?

Thank You!

**Comment by begeekmyfriend** [comment]
Yasea does nothing with HLS or any fragment. The stream is only published under RTMP. It is `nginx-rtmp` that translates the packaging protocol. I am afraid it is a bug of `nginx-rtmp` module.

**Comment by shwetanks** [comment]
Thanks! apparently the timestamp of first fragment is incorrect to be causing this.
i'll close this here and figure it on nginx-rtmp module source.

**Comment by begeekmyfriend** [comment]
You can dump all time stamp in [RTMP module](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/com/github/faucamp/simplertmp/io/RtmpConnection.java#L427) to check whether they are correct or not.

**Comment by shubhapp** [comment]
This happens when there is a lag between audio and video frames while 

` I/SrsFlvMuxer: worker: send frame type=9, dts=302, size=131072B
/RtmpConnection: wrote packet: RTMP Video, size: 19993
/RtmpConnection: wrote packet: RTMP Video, size: 3525
D/RtmpConnection: wrote packet: RTMP Video, size: 2473
D/RtmpConnection: wrote packet: RTMP Audio, size: 11
D/RtmpConnection: wrote packet: RTMP Audio, size: 192
 D/RtmpConnection: wrote packet: RTMP Audio, size: 192`

in above logs, you can see we have a noticeable lag between audio and video frame.what are the possible reason for it and how can we solve this?

**Comment by shwetanks** [comment]
Hi Leo..we did some research on this on several devices and narrowed it down to 32 bit devices on which we can consistently recreate the issue.
there also are some 64 bit devices e.g. Oppo (64bit) and Lenovo (64bit)

**Comment by begeekmyfriend** [comment]
I have expanded the PCM sampling buffer. Please try this [commit](https://github.com/begeekmyfriend/yasea/commit/3d21b722f9c8d7796c19d2709c94ea198b8f95cf)

**Comment by begeekmyfriend** [comment]
Did you sync the latest version or have you tried some other RTMP server like [SRS 2.0 release](https://github.com/ossrs/srs/tree/2.0release)?

**Comment by shwetanks** [comment]
thanks Leo, will update you shortly..we're on it (using expanded PCM buffer)
nginx-rtmp is pretty much integrated with our wide delivery network but we're looking into other options as well to plug this gap on servers

**Comment by shwetanks** [comment]
11-21 16:46:54.785 4160-4866/com.myapp E/AndroidRuntime: FATAL EXCEPTION: Thread-1442
                                                                       Process: com.myapp, PID: 4160
                                                                       java.nio.BufferOverflowException
                                                                           at java.nio.Buffer.checkPutBounds(Buffer.java:183)
                                                                           at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:356)
                                                                           at net.ossrs.yasea.SrsEncoder.onGetPcmFrame(SrsEncoder.java:354)
                                                                           at net.ossrs.yasea.SrsPublisher$2.run(SrsPublisher.java:118)
                                                                           at java.lang.Thread.run(Thread.java:818)
11-21 16:46:54.804 756-4764/? E/mm-camera: <ISP   ><ERROR> 1965: isp_util_update_hw_param: saved zoom level:0


-- sorry this didn't work out. we'll keep trying. thanks for help!

**Comment by begeekmyfriend** [comment]
It seems that the PCM buffer size has to be 4096 for microphone reading.

**Comment by begeekmyfriend** [comment]
FYI #554

**Comment by smolyakoff** [comment]
@shwetanks, did you manage to find any solution for this issue?

**Comment by leeapted** [comment]
I'm also very interested in any solutions.
