### ISSUE TITLE
ANR Issues while loading the application

### ISSUE THREAD

**Issue by sabodh** [begeekmyfriend/yasea#504]
```
FATAL EXCEPTION: GLThread 5248                                                                         
                                                                         java.lang.RuntimeException: Camera is being used after Camera.release() was called
                                                                             at android.hardware.Camera.setPreviewTexture(Native Method)
                                                                             at net.ossrs.yasea.SrsCameraView.onSurfaceCreated(SrsCameraView.java:90)
                                                                             at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1521)
                                                                             at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1253)
```

Getting this error at  run time and application stops unexpectedly.
How can i remove call backs from the  SrsCameraView ? 
or what is the solution for  this camera issues

**Comment by begeekmyfriend** [comment]
at net.ossrs.yasea.SrsCameraView.onSurfaceCreated([SrsCameraView.java:90](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsCameraView.java#L90))

Please clone the latest version and try again.

**Comment by sabodh** [comment]
I am using the latest version .

**Comment by sabodh** [comment]
Camera view doesn't  move to landscape mode if I put the code in main activity.
        setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);
it convert only the layout to landscape . Why this problem?

**Comment by begeekmyfriend** [comment]
It seems you are not quite familiar with Android development. This is not an issue of yasea SDK...

**Comment by sabodh** [comment]
👍
