### ISSUE TITLE
App getting crash on click publish button

### ISSUE THREAD

**Issue by Sameeksha23** [begeekmyfriend/yasea#521]
Hi,

Getting below error on click publish button when I implement yasea library in my project. 

Process: com.zecast.zecast_live, PID: 19134
                                                                        java.lang.UnsatisfiedLinkError: No implementation found for void net.ossrs.yasea.SrsEncoder.setEncoderResolution(int, int) (tried Java_net_ossrs_yasea_SrsEncoder_setEncoderResolution and Java_net_ossrs_yasea_SrsEncoder_setEncoderResolution__II)
                                                                            at net.ossrs.yasea.SrsEncoder.setEncoderResolution(Native Method)
                                                                            at net.ossrs.yasea.SrsEncoder.start(SrsEncoder.java:107)
                                                                            at net.ossrs.yasea.SrsPublisher.startEncode(SrsPublisher.java:148)
                                                                            at net.ossrs.yasea.SrsPublisher.startPublish(SrsPublisher.java:167)
                                                                            at com.zecast.zecast_live.activity.YeastActivity$1.onClick(YeastActivity.java:90)
                                                                            at android.view.View.performClick(View.java:4764)
                                                                            at android.view.View$PerformClick.run(View.java:19844)
                                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:135)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5297)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)

**Comment by begeekmyfriend** [comment]
Because the native methods could not be [registered](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/cpp/libenc/libenc.cc#L581).
