### ISSUE TITLE
Fail to connect to camera service

### ISSUE THREAD

**Issue by Kristaps89** [begeekmyfriend/yasea#523]
I got this error.
App is working on Samsung but that is crashed on another phone.
Caused by java.lang.RuntimeException: Fail to connect to camera service
       at android.hardware.Camera.<init>(Camera.java:568)
       at android.hardware.Camera.open(Camera.java:405)
       at net.ossrs.yasea.SrsCameraView.openCamera(SrsCameraView.java:356)
       at net.ossrs.yasea.SrsCameraView.setPreviewResolution(SrsCameraView.java:141)
       at net.ossrs.yasea.SrsPublisher.setPreviewResolution(SrsPublisher.java:229)

in SrsCameraView class,  I see private Camera mCamera;
I think that this bug is related with using deprecated Camera sdk.
please let me know how can I fix it.

**Comment by begeekmyfriend** [comment]
No, that is because your camera does not support preview resolution as 640x360. Try 640x480 in [MainActivity.java](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/yasea/demo/MainActivity.java#L74)

**Comment by Kristaps89** [comment]
[com.thinapp.peepo_issue_1_crash_59B8A2530391000125807D639FDDC082_b1828635983111e7980956847afe9799_0_v2.txt](https://github.com/begeekmyfriend/yasea/files/1298033/com.thinapp.peepo_issue_1_crash_59B8A2530391000125807D639FDDC082_b1828635983111e7980956847afe9799_0_v2.txt)

I changed resolution  as 640x480.   but app is still crashed.
Phone is Samsung Galaxy Sol,  android version is 6.0.1

**Comment by begeekmyfriend** [comment]
Please invoke `mCamera.getParameters().getSupportedPreviewSizes()` and `mCamera.getParameters().getSupportedPictureSizes` to find out what is the proper preview resolution should be set.

**Comment by Kristaps89** [comment]
Why doesn't this sdk show any permission dialog such as camera access.?
I tried with default resolution but app is crashed.

**Comment by Kristaps89** [comment]
OK, I resolved this problem.
I call Manifest.permission.CAMERA and Manifest.permission.RECORD_AUDIO manually.
now it works fine.

**Comment by Mgldog** [comment]
> OK, I resolved this problem.
> I call Manifest.permission.CAMERA and Manifest.permission.RECORD_AUDIO manually.
> now it works fine.

I use the same way to resolve my question.
