### ISSUE TITLE
Audio is flickering while streaming to Youtube 

### ISSUE THREAD

**Issue by thakurmayu07** [begeekmyfriend/yasea#554]
I can successfully live stream on youtube by using this library but the audio quality of uploaded video is not so good. It is flickering. How can I solve that?

**Comment by begeekmyfriend** [comment]
I have expanded the PCM sampling buffer. Please try this [commit](https://github.com/begeekmyfriend/yasea/commit/3d21b722f9c8d7796c19d2709c94ea198b8f95cf)

**Comment by thakurmayu07** [comment]
Hi, Thanks for the reply. I did exactly what you have committed but I got **BufferOverflowException** 
Below is the error log report
```
java.nio.BufferOverflowException
at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:264)
at net.ossrs.yasea.SrsEncoder.onGetPcmFrame(SrsEncoder.java:354)
at net.ossrs.yasea.SrsPublisher$2.run(SrsPublisher.java:108)
at java.lang.Thread.run(Thread.java:761)
```

**Comment by thakurmayu07** [comment]
Hi, when I set **mPcmBuffer** byte array size in **SrsPublisher.java** to **_16384_** it gives me **BufferOverflowException** on bb.put(data, 0, size); in  onGetPcmFrame(byte[] data, int size) method. But when I set **mPcmBuffer** to **_4096_** it works fine. Please help.

**Comment by begeekmyfriend** [comment]
I am afraid 4096 is the limitation for microphone reading.

**Comment by thakurmayu07** [comment]
Yes, you were right. **1 frame of a Stereo 48khz 16bit PCM stream is 4 bytes.** So to fix the flickering of sound I changed the audio sampling rate to 16KHz and audio bit rate to 64kbps. Now sound is smooth while streaming.

**Comment by begeekmyfriend** [comment]
But the sampling frequency is 44.1K by default.

**Comment by thakurmayu07** [comment]
Yes I changed it to 16000

**Comment by st4ycool** [comment]
Same problem here.
@thakurmayu07 so, the problem is solved? Can you link a commit?

**Comment by begeekmyfriend** [comment]
@st4ycool You may change this [line](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsEncoder.java#L38)

**Comment by thakurmayu07** [comment]
@st4ycool As @begeekmyfriend has mentioned it, change it to 16000

**Comment by st4ycool** [comment]
@begeekmyfriend 16khz doesnt really solve the problem. Here is stream with 16khz audio: https://www.youtube.com/watch?v=3ZXoZMTezmk

@thakurmayu07 have you tried to go below 16k? My MediaCodec crashes if there are lower values

**Comment by st4ycool** [comment]
It seems to me the issue is in AAC part. ADTS headers writes in some wrong way

**Comment by begeekmyfriend** [comment]
The ADTS writing code is [here](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsFlvMuxer.java#L831). Would you please show me anything wrong?

**Comment by st4ycool** [comment]
I don't know what exactly wrong, I am trying to solve it for a while. Maybe they are written too often?

**Comment by begeekmyfriend** [comment]
ADTS is only for AAC-LC. It works all right for other players except Youtube. What kind of format of AAC for Youtube? AAC-HE or AAC-HEv2?

**Comment by st4ycool** [comment]
No details provided by youtube... does it mean they accept any of them?
https://i.imgur.com/vHgNvC0.jpg
https://support.google.com/youtube/answer/2853702?hl=en

**Comment by begeekmyfriend** [comment]
@st4ycool @thakurmayu07 Two ways:
- Comment out these [two lines](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsFlvMuxer.java#L795-L796) in main branch and see if it is all right on Youtube.
- Switch to the [aac-hev2](https://github.com/begeekmyfriend/yasea/tree/aac-hev2) branch and see the result.
Note both of two ways above are not compatible with some old flash media players.

**Comment by st4ycool** [comment]
@begeekmyfriend 

I tried streaming using both solutions, but it didn't solve issue. But I noticed something very strange:

When I stream LIVE I hear audio flickering, but when youtube saves live stream to videos, it sounds OK. Why? 

I was streaming with 4g, and watching my live stream with wired 100mbps, so it's for sure not the bandwidth problem.

It looks like youtube cant decode quickly enough?

**Comment by st4ycool** [comment]
yasea he v2 24000: youtube stream is not starting.
yasea he v2 44100: youtube stream is not starting.
yasea master 16000: stream is ok, audio is ok(I swear yesterday audio was flickering), also youtube says to set audio sampling rate to 41.1khz or 48khz

What can be wrong with youtube when sample rate is 41.1?

**Comment by begeekmyfriend** [comment]
Never sound 41.1K, maybe the best choice is 48K for you...

**Comment by st4ycool** [comment]
My bad, I meant 44.1khz, of course.
48k is flickering.

**Comment by st4ycool** [comment]
@begeekmyfriend 
I still havent found a solution. 
Why we have MediaCodec converting PCM to aac, and why we have to add adts manually?

**Comment by begeekmyfriend** [comment]
PCM is the format for voice sampling.
ADTS header is for AAC-LC and necessary for decoding. But it would not be produced automatically by `MediaCodec`.

**Comment by st4ycool** [comment]
@begeekmyfriend 
I dont those parts of header in yeasea's writeAdtsHeader: https://i.imgur.com/OOKGZ7c.jpg

**Comment by st4ycool** [comment]
That's how I hear it on youtube stream LIVE:
[Recording (35).zip](https://github.com/begeekmyfriend/yasea/files/1720634/Recording.35.zip)

**Comment by begeekmyfriend** [comment]
I forgot to tell you that ADTS is for conventional flash media player.

**Comment by st4ycool** [comment]
@begeekmyfriend I can start youtube stream without ADTS, but it sounds same terrible when live.
What can be wrong, keeping in mind that autosaved stream's sound is perfect?

**Comment by begeekmyfriend** [comment]
Try it
> ffmpeg -re -i test.mp4 -vcodec libx264 -acodec libfdk_aac -f flv rtmp://youtube.com/app/stream

**Comment by thakurmayu07** [comment]
@st4ycool @begeekmyfriend Have you found any solution? Live stream with 16K sampling frequency also creates noise when audio is loud or multiple persons are talking. Also I observed that voice is cutting after every 2-3 seconds.

**Comment by st4ycool** [comment]
@thakurmayu07 the thing is YouTube can't decode yasea's AAC fast enough to broadcast without audio lags (because auto-saved video is fine). So I think the only solution is to improve/replace the AAC part.

I ve been streaming on facebook and there is no such problem like audio lags.

**Comment by thakurmayu07** [comment]
As I can see in SrsEncoder class the audio codec is "audio/mp4a-latm". Can we change it to something else?

**Comment by thakurmayu07** [comment]
![image](https://user-images.githubusercontent.com/14952711/37133950-16be08d2-22bc-11e8-8e6a-5d35c321c8c9.png)

We need this configuration

**Comment by begeekmyfriend** [comment]
You can try on your own. I think it is the issue of Youtube not the streaming.

**Comment by thakurmayu07** [comment]
Hi guys, I have found the issue. The library is fantastic, you just need to set latency to normal in YouTube admin panel. For more details : [https://support.google.com/youtube/answer/7444635?hl=en](url)

![yasea](https://user-images.githubusercontent.com/14952711/37390026-78196c78-278c-11e8-8b19-63eba0f346da.png)

**Comment by st4ycool** [comment]
@thakurmayu07 genius. How could it have been so easy? Wow! Thank you!
Tell me how you decided to try adjust some settings?

I always thought it was something with audio codecs. Sorry, @begeekmyfriend , your codecs are shiny!

**Comment by begeekmyfriend** [comment]
Unfortunately I do not get access to Youtube quite conveniently in China you know it...

**Comment by st4ycool** [comment]
@begeekmyfriend I totally forgot about China firewall. 
Thanks for support.

**Comment by thakurmayu07** [comment]
@st4ycool I was going in details about the requirements of video stream. There I found latency settings. I changed that from admin panel and boom! everything works like charm. 

@begeekmyfriend This library is awesome. As we understand the issue and come to know that library doesn't do anything wrong, you can close this thread now.

**Comment by begeekmyfriend** [comment]
@thakurmayu07 Better keep it open and let someone know it.

**Comment by thakurmayu07** [comment]
@begeekmyfriend Yes, Sure.

**Comment by huongtran84** [comment]
set latency to normal not resolved for me.do you have another solution.my audio still flickering

**Comment by huongtran84** [comment]
But I need low latency and ultra low latency because of An ultra-low-latency stream further reduces the time it takes for video to be visible to viewers, making interaction with viewers easier.What I need changed to remove noising flicker. @begeekmyfriend  @thakurmayu07 @st4ycool

**Comment by huongtran84** [comment]
> Hi guys, I have found the issue. The library is fantastic, you just need to set latency to normal in YouTube admin panel. For more details : https://support.google.com/youtube/answer/7444635?hl=en
> 
> ![yasea](https://user-images.githubusercontent.com/14952711/37390026-78196c78-278c-11e8-8b19-63eba0f346da.png)

But I still need low latency and ultra low latency because of An ultra-low-latency stream further reduces the time it takes for video to be visible to viewers, making interaction with viewers easier.If I use normal latency long time.

**Comment by maniacs-engineerica** [comment]
@thakurmayu07 , I am trying to stream to Youtube too, but it is not working. The logcat is no showing errors, so it seems to work fine. I think the problem is regarding the authentication. How do you push to the rtmp link being authenticated?

Thanks in advance.

**Comment by huongtran84** [comment]
long time I still not resolve audio flicker while using youtube with ultra low latency mode.any one help me.

**Comment by kostyaBoss** [comment]
getting same trouble with AWS MediaLive service. When streaming from obs everything seems to be fine

**Comment by kostyaBoss** [comment]
@begeekmyfriend thanks for quick responding. Maybe you know what exactly should I configure? Stub with this issue for 2 days right now

**Comment by begeekmyfriend** [comment]
@kostyaBoss In China it is hard to connect with AWS. The reason you know...

**Comment by kostyaBoss** [comment]
@begeekmyfriend after some research I've found that the problem is in default google encoder. If I am setting force to harware everything goes fine. Btw it also fixes YouTube problem. But it works only on some devices (for ex Samsung) which have their own encoder. How do you think, is it possible to make some expanding and install custom encoder on runtime?

**Comment by begeekmyfriend** [comment]
@kostyaBoss Your issue is out of my knowledge but the information you provided might be very valuable for others.

**Comment by mhackeras** [comment]
by searching and using some of the examples above.. audio is not fine. still same problem..

**Comment by axelbartolomei** [comment]
@kostyaBoss I found that **useSoftEncoder** in **SrsEncoder** class is **false** by default.

`private boolean useSoftEncoder = false;`

Is this the forcing that you're talking about?
Unfortunately useSoftEncoder = false does not work for me, audio is still flickering.

Any other ideas?

N.B.: I'm trying to stream to AWS MediaLive service

**Comment by mhackeras** [comment]
@axelbartolomei  did you try enable it and test?

**Comment by heaveninfosoft** [comment]
@thakurmayu07  how to live stream to youtube>?? i cant please help me
