### ISSUE TITLE
Crash after opening stock camera

### ISSUE THREAD

**Issue by kabunov** [begeekmyfriend/yasea#565]
Hi, firstly thanks for your library )
Found a bug, could you check how to fix it?

Steps to reproduce:
1) Open the sample yasea app
2) Hide the app and open stock android camera app (or any other app which is used camera/camera2 api)
3) Open the yasea app again
4) Observe - the preview is not working, when trying to click Switch Camera - crash.

`12-14 10:25:06.912 11657-11657/net.ossrs.yasea.demo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: net.ossrs.yasea.demo, PID: 11657
                                                                      java.lang.RuntimeException: getParameters failed (empty parameters)
                                                                          at android.hardware.Camera.native_getParameters(Native Method)
                                                                          at android.hardware.Camera.getParameters(Camera.java:1952)
                                                                          at net.ossrs.yasea.SrsCameraView.stopTorch(SrsCameraView.java:410)
                                                                          at net.ossrs.yasea.SrsCameraView.stopCamera(SrsCameraView.java:324)
                                                                          at net.ossrs.yasea.SrsPublisher.switchCameraFace(SrsPublisher.java:275)
                                                                          at net.ossrs.yasea.demo.MainActivity$2.onClick(MainActivity.java:112)
                                                                          at android.view.View.performClick(View.java:6213)
                                                                          at android.widget.TextView.performClick(TextView.java:11074)
                                                                          at android.view.View$PerformClick.run(View.java:23645)
                                                                          at android.os.Handler.handleCallback(Handler.java:751)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6692)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)`

**Comment by begeekmyfriend** [comment]
Change the resolution into 640p.

**Comment by kabunov** [comment]
>Change the resolution into 640p.

What do you mean? I haven't change any resolution, used default

        mPublisher.setPreviewResolution(640, 360);
        mPublisher.setOutputResolution(360, 640);

**Comment by begeekmyfriend** [comment]
I mean try 640x480p...

**Comment by kabunov** [comment]
Tried

    mPublisher.setPreviewResolution(640, 480);
    mPublisher.setOutputResolution(480, 640);

the same error

**Comment by begeekmyfriend** [comment]
I am afraid it is because the camera had not been released    by other app when reopening yasea.

**Comment by kabunov** [comment]
I tried different apps with camera functions (as well as device's stock cameras), on both my devices Nexus 5 (android 6) and Galaxy S7 (android 7). It's reproduced 100% times.
Right now I'm trying to implement "library" module to my app, but I think it will also crash, since the sample app crashes in this scenario.
Have you been able to reproduce this? I can create a video if needed.

**Comment by begeekmyfriend** [comment]
Do you understand what my mean on releasing camera by app? A camera object cannot be used until it is released by  its last user bu callin release method.
