### ISSUE TITLE
装在一体机上面，运行一会后就会内存溢出，这个怎么办？

### ISSUE THREAD

**Issue by Murphy-Tong** [begeekmyfriend/yasea#571]
java.lang.OutOfMemoryError: Failed to allocate a 131084 byte allocation with 112780 free bytes and 110KB until OOM
	at net.ossrs.yasea.SrsAllocator$Allocation.<init>(SrsAllocator.java:13)
	at net.ossrs.yasea.SrsAllocator.allocate(SrsAllocator.java:98)
	at net.ossrs.yasea.SrsFlvMuxer$SrsRawH264Stream.muxFlvTag(SrsFlvMuxer.java:584)
	at net.ossrs.yasea.SrsFlvMuxer$SrsFlv.writeH264IpbFrame(SrsFlvMuxer.java:954)
	at net.ossrs.yasea.SrsFlvMuxer$SrsFlv.writeVideoSample(SrsFlvMuxer.java:910)
	at net.ossrs.yasea.SrsFlvMuxer.writeSampleData(SrsFlvMuxer.java:214)
	at net.ossrs.yasea.ScreenRecoder.recordVirtualDisplay(ScreenRecoder.java:164)
	at net.ossrs.yasea.ScreenRecoder.run(ScreenRecoder.java:339)

**Comment by begeekmyfriend** [comment]
Allocator是防止GC引起的内存抖动而设置的，会影响性能。
如果发生OOM的话，需要你改动源代码去掉Allocator。

**Comment by Yotakot** [comment]
@begeekmyfriend  Allocator 被使用的地方太多了，如何去掉，能不能给个思路

**Comment by begeekmyfriend** [comment]
内存多大？

**Comment by Yotakot** [comment]
@begeekmyfriend   2GB内存，1080P，65寸屏幕

**Comment by Yotakot** [comment]
@begeekmyfriend  这个如果运行在X86机器上面会出现什么问题吗，大佬

**Comment by begeekmyfriend** [comment]
2GB？照理说Allocator不会引发内存泄漏，不可能OOM的。你用Android Studio跑一下，在上面看看CPU和memmory（你会用AS的吧）
