### ISSUE TITLE
App运行一段时间会 crash

### ISSUE THREAD

**Issue by cnliusen** [begeekmyfriend/yasea#573]
```
01-09 14:38:36.240 E/ACodec  (10612): [OMX.Intel.hw_ve.h264] ERROR(0x80001001)
01-09 14:38:36.240 E/ACodec  (10612): signalError(omxError 0x80001001, internalError -2147483648)
01-09 14:38:36.240 E/MediaCodec(10612): Codec reported err 0x80001001, actionCode 0, while in state 6
--------- beginning of crash
01-09 14:38:36.279 E/AndroidRuntime(10612): FATAL EXCEPTION: Thread-110
01-09 14:38:36.279 E/AndroidRuntime(10612): Process: com.xxxxxxx.xxx, PID: 10612
01-09 14:38:36.279 E/AndroidRuntime(10612): java.lang.IllegalStateException
01-09 14:38:36.279 E/AndroidRuntime(10612):     at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
01-09 14:38:36.279 E/AndroidRuntime(10612):     at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:983)
01-09 14:38:36.279 E/AndroidRuntime(10612):     at net.ossrs.yasea.SrsEncoder.onProcessedYuvFrame(SrsEncoder.java:301)
01-09 14:38:36.279 E/AndroidRuntime(10612):     at net.ossrs.yasea.SrsEncoder.onGetRgbaFrame(SrsEncoder.java:383)
01-09 14:38:36.279 E/AndroidRuntime(10612):     at net.ossrs.yasea.SrsPublisher$1.onGetRgbaFrame(SrsPublisher.java:42)
01-09 14:38:36.279 E/AndroidRuntime(10612):     at net.ossrs.yasea.SrsCameraView$4.run(SrsCameraView.java:232)
01-09 14:38:36.279 E/AndroidRuntime(10612):     at java.lang.Thread.run(Thread.java:818)
```

我在做一个长时间持续推流的app。有的时候运行30分钟会crash，有的时候运行几个小时会crash。

**Comment by begeekmyfriend** [comment]
估计你的ROM是定制的

**Comment by cnliusen** [comment]
@begeekmyfriend 谢谢回复。我确实用的是个第三方的Rom，请问你是怎么看出来的。这个error意味着什么呢？

**Comment by begeekmyfriend** [comment]
意味着你的`MediaCodec`硬编码类库特性不稳定，切换到软编码试试

**Comment by cnliusen** [comment]
@begeekmyfriend 我试过软编码了，软编码占得CPU和memory太高了，我的软件还需要做大量的其他运算。我可能会试试catch media codec的run time error。如果有run time error就直切重启media codec。
