### ISSUE TITLE
 FATAL EXCEPTION - 

### ISSUE THREAD

**Issue by nok91** [begeekmyfriend/yasea#576]
Error generated when I tried to publish.
Device: huawei p8

/AndroidRuntime: FATAL EXCEPTION: Thread-1052

Process: com.fuush.fuush_android, PID: 28996

 java.lang.IllegalStateException  at 
android.media.MediaCodec.native_dequeueInputBuffer(Native Method)  at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2346) at net.ossrs.yasea.SrsEncoder.onProcessedYuvFrame(SrsEncoder.java:301) at net.ossrs.yasea.SrsEncoder.onGetRgbaFrame(SrsEncoder.java:383) at net.ossrs.yasea.SrsPublisher$1.onGetRgbaFrame(SrsPublisher.java:42) at net.ossrs.yasea.SrsCameraView$4.run(SrsCameraView.java:232) at

**Comment by begeekmyfriend** [comment]
Custom ROM is usually not compatible with `MediaCodec`. Please switch to soft encoding.

**Comment by nok91** [comment]
Switch in to soft encoding displayed this issues:

>Toast: Invalid RTMP URL. Must be in format: rtmp://host[:port]/application/streamName

01-12 20:58:56.983 21557-21557/net.ossrs.yasea.demo E/BufferQueueProducer: [SurfaceTexture-2-21557-0] cancelBuffer: slot 2 is not owned by the producer (state = 2)
01-12 20:58:56.984 21557-21557/net.ossrs.yasea.demo E/BufferQueueProducer: [SurfaceTexture-2-21557-0] cancelBuffer: slot 4 is not owned by the producer (state = 3)
01-12 20:58:56.984 21557-21557/net.ossrs.yasea.demo E/BufferQueueProducer: [SurfaceTexture-2-21557-0] cancelBuffer: slot 0 is not owned by the producer (state = 0)
01-12 20:58:56.984 21557-21557/net.ossrs.yasea.demo E/BufferQueueProducer: [SurfaceTexture-2-21557-0] cancelBuffer: slot 1 is not owned by the producer (state = 0)
01-12 20:58:56.984 21557-21557/net.ossrs.yasea.demo E/BufferQueueProducer: [SurfaceTexture-2-21557-0] cancelBuffer: slot 2 is not owned by the producer (state = 2)
01-12 20:58:56.984 21557-21557/net.ossrs.yasea.demo E/BufferQueueProducer: [SurfaceTexture-2-21557-0] cancelBuffer: slot 3 is not owned by the producer (state = 0)
01-12 20:58:56.985 21557-21557/net.ossrs.yasea.demo E/BufferQueueProducer: [SurfaceTexture-2-21557-0] cancelBuffer: slot 4 is not owned by the producer (state = 3)

**Comment by begeekmyfriend** [comment]
What is the format of your URL?

**Comment by nok91** [comment]
rtmp://52.14.63.214/live/-L2wElZLVDPyNbZGoGKl

**Comment by begeekmyfriend** [comment]
There is a `-` character...
I have imported RTMP module from another open source project where there is a [regular expression](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/com/github/faucamp/simplertmp/io/RtmpConnection.java#L47) for RTMP URL parsing. Unfortunately I am not familiar with the regular expression. I am afraid you need to debug on your own. Sorry about that.

**Comment by RobRoseKnows** [comment]
@begeekmyfriend That regex should evaluate correctly. You can use [this tool](https://www.regexplanet.com/advanced/java/index.html) to check.

**Comment by begeekmyfriend** [comment]
Any PR is welcome if anyone fix such bug...
