### ISSUE TITLE
关于 5.0 以下支持，有两个疑问。

### ISSUE THREAD

**Issue by autismbug92** [begeekmyfriend/yasea#588]
您好，在使用过程中，遇到两个疑问，希望您能够帮忙解答，谢谢。
#### 1.红米2 Android4.4.4手机。拉取了 android-16 分支，推流时，抛出如下异常,是因为这个处理器版本不支持吗？
```
01-30 16:43:33.218 4332-4332/com.yuancore.sepia D/dalvikvm: Trying to load lib /data/app-lib/com.yuancore.sepia-1/libyuv.so 0x422fa1e8
01-30 16:43:33.218 4332-4332/com.yuancore.sepia D/dalvikvm: Added shared lib /data/app-lib/com.yuancore.sepia-1/libyuv.so 0x422fa1e8
01-30 16:43:33.218 4332-4332/com.yuancore.sepia D/dalvikvm: No JNI_OnLoad found in /data/app-lib/com.yuancore.sepia-1/libyuv.so 0x422fa1e8, skipping init
01-30 16:43:33.218 4332-4332/com.yuancore.sepia D/dalvikvm: Trying to load lib /data/app-lib/com.yuancore.sepia-1/libenc.so 0x422fa1e8
01-30 16:43:33.218 4332-4332/com.yuancore.sepia E/dalvikvm: dlopen("/data/app-lib/com.yuancore.sepia-1/libenc.so") failed: dlopen failed: cannot locate symbol "stpcpy" referenced by "libenc.so"...
01-30 16:43:33.218 4332-4332/com.yuancore.sepia W/dalvikvm: Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lnet/ossrs/yasea/SrsEncoder;
01-30 16:43:33.218 4332-4332/com.yuancore.sepia D/AndroidRuntime: Shutting down VM
01-30 16:43:33.218 4332-4332/com.yuancore.sepia W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x4165dd58)
01-30 16:43:33.228 4332-4332/com.yuancore.sepia E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: com.yuancore.sepia, PID: 4332
                                                                  java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "stpcpy" referenced by "libenc.so"...
                                                                      at java.lang.Runtime.loadLibrary(Runtime.java:364)
                                                                      at java.lang.System.loadLibrary(System.java:526)
                                                                      at net.ossrs.yasea.SrsEncoder.<clinit>(SrsEncoder.java:635)
                                                                      at net.ossrs.yasea.SrsPublisher.setEncodeHandler(SrsPublisher.java:303)
                                                                      at com.yuancore.sepia.modular.view.YCSepiaActivity.h(YCSepiaActivity.java:312)
                                                                      at com.yuancore.sepia.modular.view.YCSepiaActivity.m(YCSepiaActivity.java:53)
                                                                      at com.yuancore.sepia.modular.view.YCSepiaActivity$9.a(YCSepiaActivity.java:549)
                                                                      at com.yuancore.sepia.a.d$1.onAction(PermissionManager.java:50)
                                                                      at com.yanzhenjie.permission.LRequest.callbackSucceed(LRequest.java:101)
                                                                      at com.yanzhenjie.permission.LRequest.start(LRequest.java:89)
                                                                      at com.yuancore.sepia.a.d.a(PermissionManager.java:39)
                                                                      at com.yuancore.sepia.modular.view.YCSepiaActivity.onResume(YCSepiaActivity.java:545)
                                                                      at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1192)
                                                                      at android.app.Activity.performResume(Activity.java:5324)
                                                                      at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2780)
                                                                      at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2819)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2254)
                                                                      at android.app.ActivityThread.access$800(ActivityThread.java:141)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:136)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5113)
                                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:515)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
                                                                      at dalvik.system.NativeStart.main(Native Method)
01-30 16:44:56.538 4332-4332/com.yuancore.sepia I/Process: Sending signal. PID: 4332 SIG: 9
```
#### 2.  android-16 分支和 master 分支相比，少了 arm64-v8a 的处理器型号支持，在手机兼容性适配上，可能会存在什么问题？

**Comment by begeekmyfriend** [comment]
`arm64-v8a`的支持是从Android 21开始的，你去`ndk-bundle`的`platform`目录下看看就知道了。
至于`stpcpy`的问题，please google 'ndk stpcpy'可解决

**Comment by autismbug92** [comment]
明白了，谢谢！
