### ISSUE TITLE
某些分辨率下crash

### ISSUE THREAD

**Issue by Allansk2** [begeekmyfriend/yasea#589]
尝试public final static int width = 1080;
       public final static int height = 1440;

1080 * 1440是我手机支持的。
mPublisher.setPreviewResolution(height, width);
 mPublisher.setOutputResolution(width, height);

发生错误

Caused by: java.lang.RuntimeException: setParameters failed
                                                                       at android.hardware.Camera.native_setParameters(Native Method)
                                                                       at android.hardware.Camera.setParameters(Camera.java:1984)
                                                                       at net.ossrs.yasea.SrsCameraView.startCamera(SrsCameraView.java:311)
                                                                       at net.ossrs.yasea.SrsPublisher.startCamera(SrsPublisher.java:63)

**Comment by begeekmyfriend** [comment]
这种异常说明你的摄像头不支持该分辨率。你可以调用`getSupportedPreviewSizes`以及`getSupportedPictureSizes`验证，另外请确认前后摄像头没有搞混

**Comment by Allansk2** [comment]
请问，如果手机从portrait变到landscape， preview会变形以及旋转90，被拉长怎么解决，我尝试了把mPublisher.setPreviewResolution和setOutputResolution的宽高互换，也会造成crash。
以及在您的demo里，有个点不是特别理解，为什么setPreviewResolution和setOutputResolution的宽高是互换的？谢谢解答！
mPublisher.setPreviewResolution(640, 360);
mPublisher.setOutputResolution(360, 640);

**Comment by begeekmyfriend** [comment]
你所说的旋转、变形都是调用[libyuv](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsEncoder.java#L621-L628) API实现的
至于`setPreviewResolution`和`setOutputResolution`的宽和高，是因为安卓手机camera的采样与显示差了90度，你去看看安卓camera文档就知道了
