### ISSUE TITLE
你好，请问两个摄像头同时推流应该怎么配置呢？

### ISSUE THREAD

**Issue by imxiaopeng** [begeekmyfriend/yasea#593]

**Comment by begeekmyfriend** [comment]
你的手机支持两个摄像头同时默认录制功能吗？

**Comment by imxiaopeng** [comment]
我是用的android开发板做的测试，支持的

**Comment by begeekmyfriend** [comment]
我只做过手机，我手头没有开发版，你可以考虑写个demo，将采集画面拼接成一幅图像送到[mEncoder.onGetRgbaFrame](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsPublisher.java#L42)这样的接口中去

**Comment by imxiaopeng** [comment]
感谢回复！我明天写个demo看下！

**Comment by imxiaopeng** [comment]
你好，我尝试着构造两个SrsPublisher对象然后将两个摄像头分别publish至两个URL，但是程序报错：
E/ACodec: Unable to instantiate decoder 'OMX.amlogic.video.encoder.avc'.
 E/MediaCodec: Codec reported an error. (omx error 0x80001003, internalError -2147483648)
W/System.err: java.io.IOException: Failed to allocate component instance
W/System.err:     at android.media.MediaCodec.createByCodecName(MediaCodec.java:204)
我的理解是MediaCodec编码器不能被创建两次；然后我把MediaCodec对象声明静态，判断null的时候才去MediaCodec.createByCodecName和configure，运行后程序崩溃，日志如下：
E/OmxVideoEncoder: setParameter: StoreMetadataInBuffersParams.nPortIndex not input port!
E/OMXNodeInstance: OMX_SetParameter() failed for StoreMetaDataInBuffers: 0x8000101b
net.ossrs.yasea.demo E/ACodec: [OMX.amlogic.video.encoder.avc] storeMetaDataInBuffers (output) failed w/ err -2147483648
E/OMXNodeInstance: OMX_EnableAndroidNativeBuffers failed with error -2147479526 (0x8000101a)
net.ossrs.yasea.demo E/AndroidRuntime: FATAL EXCEPTION: main
Process: net.ossrs.yasea.demo, PID: 6844
java.lang.IllegalStateException: start failed
at android.media.MediaCodec.start(Native Method)
at net.ossrs.yasea.SrsEncoder.start(SrsEncoder.java:182)
如果可以请教我怎么解决，谢谢！

**Comment by begeekmyfriend** [comment]
你的意思就是分别推送到两个URL是吗？`MediaCodec`只能创建一次，你这样必须需要开多线程共享，还需要确认哪一帧H.264送到哪个地址，很麻烦的。鉴于你的复杂需求，我无法提供可靠的答案

**Comment by imxiaopeng** [comment]
是的，多路推流。

**Comment by imxiaopeng** [comment]
好的，明白，感谢解答！

**Comment by notedit** [comment]
我们之前做过一个双摄像头的项目  把两个摄像头拼接成一个再发布

如果推两路流的话 可以考虑用软编

**Comment by daniulive** [comment]
他说的实际上是多实例推送的问题。
之前我们娃娃机的客户提出来过，我们做过处理，开发板不同于普通的android手机，两个摄像头数据是可以同时拿到的，启两个publisher实例推送即可。

**Comment by gufengye** [comment]
启两个publisher实例推送，怎么处理可以同时推送两路，现在启2路，数据都乱到一起，无法分开了。

**Comment by zhangyuanlu** [comment]
@gufengye 请问这个问题有方案了吗？

**Comment by begeekmyfriend** [comment]
有人用了多进程的方式解决了https://github.com/begeekmyfriend/yasea/issues/654
