### ISSUE TITLE
Recording Error:  Bad limit (capacity 6803)

### ISSUE THREAD

**Issue by ToysoftInc** [begeekmyfriend/yasea#597]
When I start the recording I got this error.  How to fix it and what caused it?

java.lang.IllegalArgumentException: Bad limit (capacity 6803): 11091
                                                                      at java.nio.Buffer.limit(Buffer.java:298)
                                                                      at net.ossrs.yasea.SrsMp4Muxer.writeSampleData(SrsMp4Muxer.java:810)
                                                                      at net.ossrs.yasea.SrsMp4Muxer.access$400(SrsMp4Muxer.java:63)
                                                                      at net.ossrs.yasea.SrsMp4Muxer$1.run(SrsMp4Muxer.java:137)

**Comment by begeekmyfriend** [comment]
Change your phone and try again. Note that this project has only been run on android phones.
