### ISSUE TITLE
"java.lang.NoSuchMethodError: No direct method" error when I imported 'library' into my project

### ISSUE THREAD

**Issue by RKuanysh** [begeekmyfriend/yasea#618]
Can someone help me with the following error?
```
java.lang.NoSuchMethodError: No direct method <init>(Lcom/github/faucamp/simplertmp/RtmpHandler;)V in class Lcom/github/faucamp/simplertmp/DefaultRtmpPublisher; or its super classes (declaration of 'com.github.faucamp.simplertmp.DefaultRtmpPublisher' appears in /data/app/com.myapp.android.predeploy-2/split_lib_dependencies_apk.apk)
        at net.ossrs.yasea.SrsFlvMuxer.<init>(SrsFlvMuxer.java:50)
        at net.ossrs.yasea.SrsPublisher.setRtmpHandler(SrsPublisher.java:289)
        at com.myapp.android.activity.TestActivity.onCreate(TestActivity.java:73)
        at android.app.Activity.performCreate(Activity.java:6283)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2758)
        at android.app.ActivityThread.access$900(ActivityThread.java:177)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:145)
        at android.app.ActivityThread.main(ActivityThread.java:5942)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
```

**Comment by begeekmyfriend** [comment]
Sorry for my late response. Did you add this [line](https://github.com/begeekmyfriend/yasea/blob/master/app/build.gradle#L29) into your `build.gradle` in your app project?

**Comment by safefy** [comment]
Did it but still error.

**Comment by safefy** [comment]
Added and still error. Please help

**Comment by LauJJ** [comment]
I also encountered this problem, the problem is no yasea problem,this because your local have RtmpHandler references, conflict with yasea, delete local references and it will be success

**Comment by begeekmyfriend** [comment]
Maybe you are right, please check out whether there are namespace conflicts in your project.
