### ISSUE TITLE
Needs Info 

### ISSUE THREAD

**Issue by sajjadjaved01** [begeekmyfriend/yasea#619]
Front cam works nice, but i think cam have set rotation. while switching to back cam when i move my mobile it crashes.

05-23 13:20:25.426 10417-10417/net.ossrs.yasea.demo I/SrsFlvMuxer: SrsFlvMuxer closed
05-23 13:20:25.427 10417-10417/net.ossrs.yasea.demo I/SrsMp4Muxer: SrsMp4Muxer closed
05-23 13:20:25.440 10417-13303/net.ossrs.yasea.demo I/SrsFlvMuxer: worker: disconnect ok.
05-23 13:20:25.462 10417-10417/net.ossrs.yasea.demo E/Editor: hideClipTrayIfNeeded() TextView is focused!! hideClipTray()
05-23 13:20:25.469 10417-10587/net.ossrs.yasea.demo E/Surface: getSlotFromBufferLocked: unknown buffer: 0xb8a8b7b0
05-23 13:20:28.595 10417-10417/net.ossrs.yasea.demo D/Camera: app passed NULL surface
05-23 13:20:28.666 10417-10417/net.ossrs.yasea.demo D/PhoneWindow: notifyNavigationBarColor, color=0x: ff000000, token: android.view.ViewRootImplAO$WEx@3ae6425
05-23 13:20:28.671 10417-10417/net.ossrs.yasea.demo I/Choreographer: Skipped 42 frames!  The application may be doing too much work on its main thread.
05-23 13:20:28.796 10417-10417/net.ossrs.yasea.demo D/Editor: setInputTypeforClipTray(): 0
05-23 13:20:28.839 10417-10417/net.ossrs.yasea.demo V/ViewRootImpl: Contents drawing finished : net.ossrs.yasea.demo/net.ossrs.yasea.demo.MainActivity
05-23 13:20:28.852 10417-10417/net.ossrs.yasea.demo I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@ffada66 time:30821887
    Timeline: Activity_idle id: android.os.BinderProxy@ffada66 time:30821887
05-23 13:20:57.683 10417-10417/net.ossrs.yasea.demo E/Editor: hideClipTrayIfNeeded() TextView is focused!! hideClipTray()
05-23 13:21:03.236 10417-10417/net.ossrs.yasea.demo I/SrsFlvMuxer: SrsFlvMuxer closed
05-23 13:21:03.237 10417-10417/net.ossrs.yasea.demo I/SrsMp4Muxer: SrsMp4Muxer closed
05-23 13:21:03.239 10417-13686/net.ossrs.yasea.demo I/SrsFlvMuxer: worker: disconnect ok.
05-23 13:21:03.250 10417-13531/net.ossrs.yasea.demo E/Surface: getSlotFromBufferLocked: unknown buffer: 0xb8794100
05-23 13:21:03.269 10417-10417/net.ossrs.yasea.demo E/Editor: hideClipTrayIfNeeded() TextView is focused!! hideClipTray()
05-23 13:21:03.290 10417-10587/net.ossrs.yasea.demo E/Surface: getSlotFromBufferLocked: unknown buffer: 0xb8a2fb30
05-23 13:21:05.032 10417-10417/net.ossrs.yasea.demo D/Camera: app passed NULL surface
05-23 13:21:05.062 10417-10417/net.ossrs.yasea.demo D/PhoneWindow: notifyNavigationBarColor, color=0x: ff000000, token: android.view.ViewRootImplAO$WEx@1260c85
05-23 13:21:05.065 10417-10417/net.ossrs.yasea.demo I/Choreographer: Skipped 30 frames!

**Comment by begeekmyfriend** [comment]
Try change the [resolution](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/yasea/demo/MainActivity.java#L74-L75) into 480p.

**Comment by begeekmyfriend** [comment]
That is 360p. 480p is 640x480. I guess your back camera preview resolution does not support 360p.

**Comment by sajjadjaved01** [comment]
Okay i'll check

**Comment by begeekmyfriend** [comment]
[mCamera.getParameters().getSupportedPreviewSizes](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsCameraView.java#L372) method. Note you need to switch to the camera you want to use.

**Comment by sajjadjaved01** [comment]
i have these line. 

> mPublisher = new SrsPublisher((SrsCameraView) findViewById(R.id.glsurfaceview_camera));
        mPublisher.setEncodeHandler(new SrsEncodeHandler(this));
        mPublisher.setRtmpHandler(new RtmpHandler(this));
        mPublisher.setRecordHandler(new SrsRecordHandler(this));
        mPublisher.setPreviewResolution(640, 360);
        mPublisher.setOutputResolution(360, 640);
        mPublisher.setVideoHDMode();
        mPublisher.startCamera();

after setting 360, getting this error `Fail to connect to camera service`

05-25 13:29:24.495 18215-18215/net.ossrs.yasea.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: net.ossrs.yasea.demo, PID: 18215
    java.lang.RuntimeException: Unable to start activity ComponentInfo{net.ossrs.yasea.demo/net.ossrs.yasea.demo.MainActivity}: java.lang.RuntimeException: Fail to connect to camera service
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2434)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
        at android.app.ActivityThread.access$900(ActivityThread.java:157)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5551)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
     Caused by: java.lang.RuntimeException: Fail to connect to camera service
        at android.hardware.Camera.<init>(Camera.java:549)
        at android.hardware.Camera.open(Camera.java:361)
        at net.ossrs.yasea.SrsCameraView.openCamera(SrsCameraView.java:364)
        at net.ossrs.yasea.SrsCameraView.setPreviewResolution(SrsCameraView.java:148)
        at net.ossrs.yasea.SrsPublisher.setPreviewResolution(SrsPublisher.java:229)
        at net.ossrs.yasea.demo.MainActivity.onCreate(MainActivity.java:76)
        at android.app.Activity.performCreate(Activity.java:6272)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2387)

**Comment by begeekmyfriend** [comment]
Didn't you change the preview resolution?

**Comment by sajjadjaved01** [comment]
changed

**Comment by begeekmyfriend** [comment]
480p is 640X480...I give up...
