### ISSUE TITLE
YASEA + SRS 局域网下连接失败

### ISSUE THREAD

**Issue by yicm** [begeekmyfriend/yasea#714]
**环境：**
```
SRS 2.0.6 RTMP推流
YASEA commit 0462d6dbcfa72ebcafd13a033e604f001a9eac2e
OBS RTMP推流测试工具
VLC客户端播放
局域网测试，服务器IP 192.168.1.115，使用YASEA android机IP 192.168.1.114, OBS客户端IP 192.168.1.115(同服务器)
```
**测试：**

- 使用OBS RTMP推流，用VLC成功拉流播放。
- 使用YASEA推流出现连接失败错误，已确定服务器和android机能够互相ping通，网络无问题。

**错误提示：**

```
01-19 13:15:05.021 6201-6299/net.ossrs.yasea.demo I/SrsFlvMuxer: worker: connecting to RTMP server by url=rtmp://192.168.1.115/live/livestream
01-19 13:15:05.021 6201-6299/net.ossrs.yasea.demo D/RtmpConnection: connect() called. Host: 192.168.1.115, port: 1935, appName: live, publishPath: livestream

......

01-19 13:15:08.031 6201-6299/net.ossrs.yasea.demo W/System.err: java.net.SocketTimeoutException: failed to connect to /192.168.1.115 (port 1935) from /192.168.1.114 (port 41822) after 3000ms
01-19 13:15:08.032 6201-6299/net.ossrs.yasea.demo W/System.err:     at libcore.io.IoBridge.connectErrno(IoBridge.java:185)
        at libcore.io.IoBridge.connect(IoBridge.java:130)
        at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:129)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:356)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
01-19 13:15:08.033 6201-6299/net.ossrs.yasea.demo W/System.err:     at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:357)
        at java.net.Socket.connect(Socket.java:616)
        at com.github.faucamp.simplertmp.io.RtmpConnection.connect(RtmpConnection.java:132)
        at com.github.faucamp.simplertmp.DefaultRtmpPublisher.connect(DefaultRtmpPublisher.java:22)
```
**分析：**

看了下YASEA出现错误的源代码，只是简单的Socket连接，为啥会出现错误呢？SRS配置文件使用默认的rtmp配置文件，是我SRS配置有问题吗？求助。（直接使用默认的RTMP服务器是没有出现连接失败的）：

```java
        rtmpDecoder = new RtmpDecoder(rtmpSessionInfo);
        socket = new Socket();
        SocketAddress socketAddress = new InetSocketAddress(host, port);
        try {
            // 这里连接失败
            socket.connect(socketAddress, 3000);
            inputStream = new BufferedInputStream(socket.getInputStream());
            outputStream = new BufferedOutputStream(socket.getOutputStream());
            Log.d(TAG, "connect(): socket connection established, doing handhake...");
            handshake(inputStream, outputStream);
            Log.d(TAG, "connect(): handshake done");
        } catch (IOException e) {
            e.printStackTrace();
            mHandler.notifyRtmpIOException(e);
            return false;
        }
```

**Comment by begeekmyfriend** [comment]
应该是SRS配置问题，你使用Wifi连接的吧

**Comment by yicm** [comment]
@begeekmyfriend  搞定了，防火墙的问题 , 😭
