### ISSUE TITLE
这是我最近经常碰到的一个bug

### ISSUE THREAD

**Issue by lovebluedan** [begeekmyfriend/yasea#717]
java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes(java.lang.String)' on a null object reference
	at com.github.faucamp.simplertmp.amf.AmfString.writeTo(AmfString.java:60)
	at com.github.faucamp.simplertmp.amf.AmfObject.writeTo(AmfObject.java:58)
	at com.github.faucamp.simplertmp.packets.VariableBodyRtmpPacket.writeVariableData(VariableBodyRtmpPacket.java:71)
	at com.github.faucamp.simplertmp.packets.Command.writeBody(Command.java:74)
	at com.github.faucamp.simplertmp.packets.RtmpPacket.writeTo(RtmpPacket.java:38)
	at com.github.faucamp.simplertmp.io.RtmpConnection.sendRtmpPacket(RtmpConnection.java:492)
	at com.github.faucamp.simplertmp.io.RtmpConnection.rtmpConnect(RtmpConnection.java:187)
	at com.github.faucamp.simplertmp.io.RtmpConnection.connect(RtmpConnection.java:158)
	at com.github.faucamp.simplertmp.DefaultRtmpPublisher.connect(DefaultRtmpPublisher.java:22)
	at net.ossrs.yasea.SrsFlvMuxer.connect(SrsFlvMuxer.java:100)
	at net.ossrs.yasea.SrsFlvMuxer.access$000(SrsFlvMuxer.java:22)
	at net.ossrs.yasea.SrsFlvMuxer$1.run(SrsFlvMuxer.java:134)
	at java.lang.Thread.run(Thread.java:818)
请问一下 这个是我的流出了问题吗？还是？请问您看过的话指导一下

**Comment by begeekmyfriend** [comment]
这是连接时出问题还是推流时出问题？如果是前者，可能代码在解析字符串有bug，`RtmpConnection.java`内，可以排查一下有哪些特殊字符

**Comment by lovebluedan** [comment]
嗯嗯 我发现这是连接时出现的问题，不是必然性 偶然发生，我现在在RtmpConnection 中url代码在解析字符那里加了一些日志 等我有找到问题所在的地方再处理一下 然后再跟您说下
