### ISSUE TITLE
Crash when launch app with NullPointerException

### ISSUE THREAD

**Issue by tl-yen** [begeekmyfriend/yasea#736]
## Enviroment
* master branch [4b188ba] 22 July 2019 at 17:45:54 GMT+8
* Meitu MP1718 with `Android 8.1`

## Reproduce Step
* upgrade **compileSdkVersion** and **targetSdkVersion** to `29`
* install and launch app

## Expected
It should not crash when launch app

## Actual
crash

## Log
```
2019-11-06 12:04:48.584 31880-31880/? I/zygote64: Late-enabling -Xcheck:jni
2019-11-06 12:04:48.871 31880-31880/net.ossrs.yasea.demo W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
2019-11-06 12:04:48.871 31880-31880/net.ossrs.yasea.demo W/VideoCapabilities: Unrecognized profile 2130706434 for video/avc
2019-11-06 12:04:48.874 31880-31880/net.ossrs.yasea.demo W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
2019-11-06 12:04:48.875 31880-31880/net.ossrs.yasea.demo W/VideoCapabilities: Unrecognized profile 2130706434 for video/avc
2019-11-06 12:04:48.880 31880-31880/net.ossrs.yasea.demo W/VideoCapabilities: Unsupported mime video/divx
2019-11-06 12:04:48.882 31880-31880/net.ossrs.yasea.demo W/VideoCapabilities: Unsupported mime video/divx311
2019-11-06 12:04:48.884 31880-31880/net.ossrs.yasea.demo W/VideoCapabilities: Unsupported mime video/divx4
2019-11-06 12:04:48.898 31880-31880/net.ossrs.yasea.demo W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
2019-11-06 12:04:48.901 31880-31880/net.ossrs.yasea.demo W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
2019-11-06 12:04:48.908 31880-31880/net.ossrs.yasea.demo W/VideoCapabilities: Unsupported mime video/x-ms-wmv
2019-11-06 12:04:48.910 31880-31880/net.ossrs.yasea.demo W/VideoCapabilities: Unsupported mime video/x-ms-wmv
2019-11-06 12:04:48.925 31880-31880/net.ossrs.yasea.demo W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
2019-11-06 12:04:48.925 31880-31880/net.ossrs.yasea.demo W/VideoCapabilities: Unrecognized profile 2130706434 for video/avc
2019-11-06 12:04:48.932 31880-31886/net.ossrs.yasea.demo I/zygote64: Do partial code cache collection, code=30KB, data=25KB
2019-11-06 12:04:48.932 31880-31886/net.ossrs.yasea.demo I/zygote64: After code cache collection, code=30KB, data=25KB
2019-11-06 12:04:48.932 31880-31886/net.ossrs.yasea.demo I/zygote64: Increasing code cache capacity to 128KB
2019-11-06 12:04:48.940 31880-31880/net.ossrs.yasea.demo I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
2019-11-06 12:04:48.949 31880-31880/net.ossrs.yasea.demo I/SrsEncoder: vencoder OMX.qcom.video.encoder.avc types: video/avc
2019-11-06 12:04:48.950 31880-31880/net.ossrs.yasea.demo W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
2019-11-06 12:04:48.950 31880-31880/net.ossrs.yasea.demo W/VideoCapabilities: Unrecognized profile 2130706434 for video/avc
2019-11-06 12:04:48.952 31880-31880/net.ossrs.yasea.demo I/SrsEncoder: vencoder OMX.qcom.video.encoder.avc supports color fomart 0x7fa30c04(2141391876)
2019-11-06 12:04:48.952 31880-31880/net.ossrs.yasea.demo I/SrsEncoder: vencoder OMX.qcom.video.encoder.avc supports color fomart 0x7f000789(2130708361)
2019-11-06 12:04:48.953 31880-31880/net.ossrs.yasea.demo I/SrsEncoder: vencoder OMX.qcom.video.encoder.avc supports color fomart 0x7f420888(2135033992)
2019-11-06 12:04:48.954 31880-31880/net.ossrs.yasea.demo I/SrsEncoder: vencoder OMX.qcom.video.encoder.avc supports color fomart 0x15(21)
2019-11-06 12:04:48.954 31880-31880/net.ossrs.yasea.demo I/SrsEncoder: vencoder OMX.qcom.video.encoder.avc support profile 1, level 32768
2019-11-06 12:04:48.955 31880-31880/net.ossrs.yasea.demo I/SrsEncoder: vencoder OMX.qcom.video.encoder.avc support profile 2, level 32768
2019-11-06 12:04:48.955 31880-31880/net.ossrs.yasea.demo I/SrsEncoder: vencoder OMX.qcom.video.encoder.avc support profile 8, level 32768
2019-11-06 12:04:48.956 31880-31880/net.ossrs.yasea.demo I/SrsEncoder: vencoder OMX.qcom.video.encoder.avc support profile 65536, level 32768
2019-11-06 12:04:48.956 31880-31880/net.ossrs.yasea.demo I/SrsEncoder: vencoder OMX.qcom.video.encoder.avc support profile 2130706433, level 32768
2019-11-06 12:04:48.957 31880-31880/net.ossrs.yasea.demo I/SrsEncoder: vencoder OMX.qcom.video.encoder.avc support profile 524288, level 32768
2019-11-06 12:04:48.958 31880-31880/net.ossrs.yasea.demo I/SrsEncoder: vencoder OMX.qcom.video.encoder.avc support profile 2130706434, level 32768
2019-11-06 12:04:48.958 31880-31880/net.ossrs.yasea.demo I/SrsEncoder: vencoder OMX.qcom.video.encoder.avc choose color format 0x15(21)
2019-11-06 12:04:48.965 31880-31880/net.ossrs.yasea.demo E/libc: Access denied finding property "camera.hal1.packagelist"
2019-11-06 12:04:48.958 31880-31880/net.ossrs.yasea.demo W/ssrs.yasea.demo: type=1400 audit(0.0:2039): avc: denied { read } for name="u:object_r:camera_prop:s0" dev="tmpfs" ino=19503 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=0
2019-11-06 12:04:48.966 31880-31880/net.ossrs.yasea.demo W/System.err: java.lang.RuntimeException: Unknown camera error
2019-11-06 12:04:48.966 31880-31880/net.ossrs.yasea.demo W/System.err:     at android.hardware.Camera.<init>(Camera.java:798)
2019-11-06 12:04:48.966 31880-31880/net.ossrs.yasea.demo W/System.err:     at android.hardware.Camera.open(Camera.java:585)
2019-11-06 12:04:48.966 31880-31880/net.ossrs.yasea.demo W/System.err:     at net.ossrs.yasea.SrsCameraView.openCamera(SrsCameraView.java:403)
2019-11-06 12:04:48.967 31880-31880/net.ossrs.yasea.demo W/System.err:     at net.ossrs.yasea.SrsCameraView.setPreviewResolution(SrsCameraView.java:150)
2019-11-06 12:04:48.967 31880-31880/net.ossrs.yasea.demo W/System.err:     at net.ossrs.yasea.SrsPublisher.setPreviewResolution(SrsPublisher.java:266)
2019-11-06 12:04:48.967 31880-31880/net.ossrs.yasea.demo W/System.err:     at net.ossrs.yasea.demo.MainActivity.onCreate(MainActivity.java:79)
2019-11-06 12:04:48.967 31880-31880/net.ossrs.yasea.demo W/System.err:     at android.app.Activity.performCreate(Activity.java:7034)
2019-11-06 12:04:48.967 31880-31880/net.ossrs.yasea.demo W/System.err:     at android.app.Activity.performCreate(Activity.java:7025)
2019-11-06 12:04:48.967 31880-31880/net.ossrs.yasea.demo W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1228)
2019-11-06 12:04:48.967 31880-31880/net.ossrs.yasea.demo W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2798)
2019-11-06 12:04:48.967 31880-31880/net.ossrs.yasea.demo W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2943)
2019-11-06 12:04:48.967 31880-31880/net.ossrs.yasea.demo W/System.err:     at android.app.ActivityThread.-wrap11(Unknown Source:0)
2019-11-06 12:04:48.967 31880-31880/net.ossrs.yasea.demo W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1648)
2019-11-06 12:04:48.967 31880-31880/net.ossrs.yasea.demo W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
2019-11-06 12:04:48.967 31880-31880/net.ossrs.yasea.demo W/System.err:     at android.os.Looper.loop(Looper.java:171)
2019-11-06 12:04:48.968 31880-31880/net.ossrs.yasea.demo W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6611)
2019-11-06 12:04:48.968 31880-31880/net.ossrs.yasea.demo W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-11-06 12:04:48.968 31880-31880/net.ossrs.yasea.demo W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
2019-11-06 12:04:48.968 31880-31880/net.ossrs.yasea.demo W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
2019-11-06 12:04:48.969 31880-31880/net.ossrs.yasea.demo D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
2019-11-06 12:04:48.971 31880-31880/net.ossrs.yasea.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: net.ossrs.yasea.demo, PID: 31880
    java.lang.RuntimeException: Unable to start activity ComponentInfo{net.ossrs.yasea.demo/net.ossrs.yasea.demo.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2845)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2943)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1648)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:6611)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
        at net.ossrs.yasea.SrsCameraView.setPreviewResolution(SrsCameraView.java:154)
        at net.ossrs.yasea.SrsPublisher.setPreviewResolution(SrsPublisher.java:266)
        at net.ossrs.yasea.demo.MainActivity.onCreate(MainActivity.java:79)
        at android.app.Activity.performCreate(Activity.java:7034)
        at android.app.Activity.performCreate(Activity.java:7025)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1228)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2798)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2943) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1648) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:171) 
        at android.app.ActivityThread.main(ActivityThread.java:6611) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
2019-11-06 12:04:48.980 31880-31880/? I/Process: Sending signal. PID: 31880 SIG: 9
```

**Comment by begeekmyfriend** [comment]
Please change the RTMP url since the original one has been dismissed. And I have no other available URLs. Or you might build a local server on your own.

**Comment by begeekmyfriend** [comment]
Sorry that I forgot you that it is camera switch issue. Is your phone custom one or produced by normal manufacturer?

**Comment by begeekmyfriend** [comment]
Or you can replace the camera module with Camera2 APIs. I have no such phone as well as Android driver either.

**Comment by tl-yen** [comment]
@begeekmyfriend 
I just install and launch app.
I did not click switch camera button.

My device is not custom one.

I have local **Nginx** RTMP server，
and I can publish by **FFmpeg**.

**Comment by begeekmyfriend** [comment]
Would you like to try changing the arguments of `setPreviewResolution`?

**Comment by tl-yen** [comment]
Yes, it's not work.

**Comment by begeekmyfriend** [comment]
Pardon that in the [crashed code](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsCameraView.java#L154) the `mCamera` object seems NULL. Can you debug `openCamera` method on your own?

**Comment by gabriel-TheCode** [comment]
Please help, I have the same error !

**Comment by begeekmyfriend** [comment]
@gabriel-TheCode I am unavaliable for Android development. I am afraid you need to debug on your own. The `mCamera` object is the most possible tracking object.

**Comment by zhuxinhuan** [comment]
did you fix this problem? i have same error

**Comment by yuanyuanzho** [comment]
Try to add runtime permission, I fixed mine by doing this

**Comment by begeekmyfriend** [comment]
Well many Android devices run like weirdos that we are not able to find out the root causes :-)
