### ISSUE TITLE
JNI Error in release build

### ISSUE THREAD

**Issue by Faiyyaz** [begeekmyfriend/yasea#759]
Hi, Thanks for such a great library.

The library works very well in debug mode but in release mode two of my devices are having issue upto now.

The device are Redmi 4A & Samsung M40.

The app crash with the below stacktrace

```
java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.dexter.rtmp_example-1/lib/arm64/libenc.so"
	at java.lang.Runtime.loadLibrary0(Runtime.java:989)
	at java.lang.System.loadLibrary(System.java:1562)
	at net.ossrs.yasea.SrsEncoder.<clinit>()
	at net.ossrs.yasea.g.a()
	at com.dexter.rtmp.activity.RTMPActivity.onCreate()
	at android.app.Activity.performCreate(Activity.java:6868)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2676)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2784)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1523)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6238)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
```

**Comment by begeekmyfriend** [comment]
I am afraid it depends on the custom SDK or NDK of the manufacturer. Try modifying some compiling or linking options in build scripts for adaptation.

**Comment by Faiyyaz** [comment]
It is working now actually it was happening because I had not mentioned proguard rules
