### ISSUE TITLE
Camera is being used after Camera.release()

### ISSUE THREAD

**Issue by pkxutao** [begeekmyfriend/yasea#780]
您好，我运行demo的时候（没改过任何代码），在第一次打开授权后就会报这个错，在第二次打开就没问题了，百分百必现，找了下相关代码也没法解决，不知道别人有没有遇到过，麻烦作者看看，谢谢 
java.lang.RuntimeException: Camera is being used after Camera.release() was called
        at android.hardware.Camera.setPreviewTexture(Native Method)
        at net.ossrs.yasea.SrsCameraView.onSurfaceCreated(SrsCameraView.java:94)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1539)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)

**Comment by begeekmyfriend** [comment]
用其它手机会有这个问题吗？

**Comment by susen123** [comment]
怎么解决的？？？
