### ISSUE TITLE
Android机顶盒外接摄像头，运行本项目报错ClassCastException。

### ISSUE THREAD

**Issue by jamin918** [begeekmyfriend/yasea#786]
首先很感谢作者开源这么好的项目。如标题所示，在Android机顶盒（android4.4）运行yasea-android-16这个分支编译的apk到机顶盒上，点击publish按钮报错，错误日志如下:
`10-14 15:20:21.476 26014-26249/? E/AndroidRuntime: FATAL EXCEPTION: Thread-287
    Process: net.ossrs.yasea.demo, PID: 26014
    java.lang.ClassCastException: com.github.faucamp.simplertmp.amf.AmfString cannot be cast to com.github.faucamp.simplertmp.amf.AmfNumber
        at com.github.faucamp.simplertmp.io.RtmpConnection.onSrsServerInfo(RtmpConnection.java:638)
        at com.github.faucamp.simplertmp.io.RtmpConnection.handleRxInvoke(RtmpConnection.java:591)
        at com.github.faucamp.simplertmp.io.RtmpConnection.handleRxPacketLoop(RtmpConnection.java:562)
        at com.github.faucamp.simplertmp.io.RtmpConnection.access$000(RtmpConnection.java:44)
        at com.github.faucamp.simplertmp.io.RtmpConnection$1.run(RtmpConnection.java:151)
        at java.lang.Thread.run(Thread.java:841)`       

apk运行在手机端推流是正常的。没找到类似的issues,在网上也没找到解决办法，所以麻烦作者帮我看一下这个问题。

**Comment by begeekmyfriend** [comment]
没有遇到过，你可以重写SimpleRTMP模块……正如有人所说，用C重写FlvMuxer和RTMP模块，延时**可能**会快一点

**Comment by jamin918** [comment]
简单修改了下类型转换了避免了程序崩溃，但还是不能成功推流，下面是点击publish按钮后的整个日志：

`10-14 15:56:16.268 3481-14728/net.ossrs.yasea.demo I/SrsFlvMuxer: worker: connecting to RTMP server by url=rtmp://10.8.8.179:1935/ceshi/1
10-14 15:56:16.268 3481-14728/net.ossrs.yasea.demo D/RtmpConnection: connect() called. Host: 10.8.8.179, port: 1935, appName: ceshi, publishPath: 1
10-14 15:56:16.268 3481-14729/net.ossrs.yasea.demo I/ACodec: onAllocateComponent
10-14 15:56:16.269 3481-14728/net.ossrs.yasea.demo D/RtmpConnection: connect(): socket connection established, doing handhake...
10-14 15:56:16.269 3481-14728/net.ossrs.yasea.demo D/Handshake: writeC0
10-14 15:56:16.269 3481-14728/net.ossrs.yasea.demo D/Handshake: writeC1
10-14 15:56:16.269 3481-14728/net.ossrs.yasea.demo D/Handshake: writeC1(): Calculating digest offset
10-14 15:56:16.269 3481-14728/net.ossrs.yasea.demo D/Handshake: writeC1(): (real value of) digestOffset: 102
10-14 15:56:16.269 3481-14728/net.ossrs.yasea.demo D/Handshake: writeC1(): recalculated digestOffset: 878
10-14 15:56:16.269 3481-14728/net.ossrs.yasea.demo D/Handshake: writeC1(): digestOffsetBytes: 00000066
10-14 15:56:16.269 3481-14728/net.ossrs.yasea.demo D/Handshake: partBeforeDigest(): size: 878
10-14 15:56:16.269 3481-14728/net.ossrs.yasea.demo D/Handshake: writeC1(): Writing timestamp and Flash Player version
10-14 15:56:16.269 3481-14728/net.ossrs.yasea.demo D/Handshake: partAfterDigest(): size: 626
10-14 15:56:16.269 3481-14728/net.ossrs.yasea.demo D/Handshake: copying digest offset bytes in partBeforeDigest
10-14 15:56:16.269 3481-14728/net.ossrs.yasea.demo D/Handshake: writeC1(): Calculating digest
10-14 15:56:16.270 3481-14729/net.ossrs.yasea.demo I/OMXClient: Using client-side OMX mux.
10-14 15:56:16.270 3481-14728/net.ossrs.yasea.demo D/Handshake: writeC1(): writing C1 packet
10-14 15:56:16.270 3481-14728/net.ossrs.yasea.demo D/Handshake: readS0
10-14 15:56:16.270 3481-14729/net.ossrs.yasea.demo D/HIOMX_CORE: OMX_Init :: enter!
10-14 15:56:16.270 3481-14729/net.ossrs.yasea.demo D/HIOMX_CORE: OMX_Init :: exit!
10-14 15:56:16.274 3481-14733/net.ossrs.yasea.demo I/ACodec: onAllocateComponent
10-14 15:56:16.274 3481-14733/net.ossrs.yasea.demo I/OMXClient: Using client-side OMX mux.
10-14 15:56:16.279 3481-14733/net.ossrs.yasea.demo E/ACodec: [OMX.hisi.video.encoder.avc] storeMetaDataInBuffers (output) failed w/ err -2147483648
10-14 15:56:16.280 3481-14733/net.ossrs.yasea.demo W/ACodec: Use baseline profile instead of 2 for AVC recording
10-14 15:56:16.281 3481-14733/net.ossrs.yasea.demo I/ACodec: setupVideoEncoder succeeded
10-14 15:56:16.282 3481-14728/net.ossrs.yasea.demo D/Handshake: readS1
10-14 15:56:16.282 3481-14728/net.ossrs.yasea.demo D/Handshake: readS1(): S1 total bytes read OK
10-14 15:56:16.282 3481-14728/net.ossrs.yasea.demo D/Handshake: writeC2
10-14 15:56:16.283 3481-14728/net.ossrs.yasea.demo D/Handshake: readS2
10-14 15:56:16.283 3481-14728/net.ossrs.yasea.demo D/Handshake: readS2(): S2 total bytes read OK
10-14 15:56:16.283 3481-14728/net.ossrs.yasea.demo D/RtmpConnection: connect(): handshake done
10-14 15:56:16.283 3481-14728/net.ossrs.yasea.demo D/RtmpConnection: rtmpConnect(): Building 'connect' invoke packet
10-14 15:56:16.283 3481-14738/net.ossrs.yasea.demo D/RtmpConnection: starting main rx handler loop
10-14 15:56:16.284 3481-14733/net.ossrs.yasea.demo I/ACodec: [OMX.hisi.video.encoder.avc] Allocating 2 buffers of size 460800 on input port
10-14 15:56:16.284 3481-14728/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Command (command: connect, transaction ID: 1), size: 250
10-14 15:56:16.286 3481-14733/net.ossrs.yasea.demo I/ACodec: [OMX.hisi.video.encoder.avc] Allocating 2 buffers of size 1000000 on output port
10-14 15:56:16.305 3481-14729/net.ossrs.yasea.demo I/ACodec: [OMX.google.aac.encoder] Allocating 4 buffers of size 4096 on input port
10-14 15:56:16.305 3481-14729/net.ossrs.yasea.demo I/ACodec: [OMX.google.aac.encoder] Allocating 4 buffers of size 8192 on output port
10-14 15:56:16.305 3481-14738/net.ossrs.yasea.demo D/dalvikvm: GC_FOR_ALLOC freed 2058K, 28% free 7342K/10060K, paused 20ms, total 20ms
10-14 15:56:16.306 3481-14738/net.ossrs.yasea.demo D/RtmpConnection: handleRxPacketLoop(): Setting acknowledgement window size: 2500000
10-14 15:56:16.325 3481-14738/net.ossrs.yasea.demo D/RtmpConnection: handleRxPacketLoop(): Send acknowledgement window size: 2500000
10-14 15:56:16.325 3481-14738/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Window Acknowledgment Size, size: 4
10-14 15:56:16.325 3481-14738/net.ossrs.yasea.demo D/RtmpDecoder: readPacket(): Setting chunk size to: 60000
10-14 15:56:16.327 3481-14738/net.ossrs.yasea.demo D/RtmpConnection: handleRxInvoke: Got result for invoked method: connect
10-14 15:56:16.327 3481-14738/net.ossrs.yasea.demo D/RtmpConnection: onSrsServerInfo: srsIdStr=4u86tu52
10-14 15:56:16.327 3481-14738/net.ossrs.yasea.demo D/RtmpConnection: onSrsServerInfo: srsId=com.github.faucamp.simplertmp.amf.AmfString@41b49128
10-14 15:56:16.327 3481-14728/net.ossrs.yasea.demo D/RtmpConnection: createStream(): Sending releaseStream command...
10-14 15:56:16.327 3481-14738/net.ossrs.yasea.demo D/RtmpConnection: handleRxInvoke(): 'onBWDone'
10-14 15:56:16.328 3481-14728/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Command (command: releaseStream, transaction ID: 2), size: 30
10-14 15:56:16.328 3481-14728/net.ossrs.yasea.demo D/RtmpConnection: createStream(): Sending FCPublish command...
10-14 15:56:16.328 3481-14728/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Command (command: FCPublish, transaction ID: 3), size: 26
10-14 15:56:16.328 3481-14728/net.ossrs.yasea.demo D/RtmpConnection: createStream(): Sending createStream command...
10-14 15:56:16.328 3481-14728/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Command (command: createStream, transaction ID: 4), size: 25
10-14 15:56:16.366 3481-14738/net.ossrs.yasea.demo D/RtmpConnection: handleRxInvoke: Got result for invoked method: releaseStream
10-14 15:56:16.366 3481-14738/net.ossrs.yasea.demo D/RtmpConnection: handleRxInvoke(): 'releaseStream'
10-14 15:56:16.389 3481-3481/net.ossrs.yasea.demo E/ViewRootImpl: 20170727 enable acc for view = Toast
10-14 15:56:16.406 3481-14738/net.ossrs.yasea.demo D/RtmpConnection: handleRxInvoke: Got result for invoked method: FCPublish
10-14 15:56:16.406 3481-14738/net.ossrs.yasea.demo D/RtmpConnection: handleRxInvoke(): 'FCPublish'
10-14 15:56:16.406 3481-14738/net.ossrs.yasea.demo D/RtmpConnection: handleRxInvoke: Got result for invoked method: createStream
10-14 15:56:16.406 3481-14738/net.ossrs.yasea.demo D/RtmpConnection: handleRxInvoke(): Stream ID to publish: 1
10-14 15:56:16.406 3481-14738/net.ossrs.yasea.demo D/RtmpConnection: fmlePublish(): Sending publish command...
10-14 15:56:16.406 3481-14738/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Command (command: publish, transaction ID: 0), size: 31
10-14 15:56:16.407 3481-14738/net.ossrs.yasea.demo D/RtmpConnection: handleRxInvoke(): 'onFCPublish'
10-14 15:56:16.448 3481-14738/net.ossrs.yasea.demo D/RtmpConnection: handleRxInvoke(): onStatus NetStream.Publish.Start
10-14 15:56:16.448 3481-14738/net.ossrs.yasea.demo D/RtmpConnection: onMetaData(): Sending empty onMetaData...
10-14 15:56:16.448 3481-14738/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: com.github.faucamp.simplertmp.packets.Data@41b30d98, size: 238
10-14 15:56:16.498 3481-14728/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Audio, size: 11
10-14 15:56:16.498 3481-14728/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Audio, size: 192
10-14 15:56:16.576 3481-14728/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Audio, size: 273
10-14 15:56:16.576 3481-14728/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Audio, size: 220
10-14 15:56:16.656 3481-14728/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Audio, size: 213
10-14 15:56:16.658 3481-14728/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Audio, size: 257
10-14 15:56:16.658 3481-14728/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Audio, size: 214
10-14 15:56:16.658 3481-14728/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Audio, size: 207
10-14 15:56:16.659 3481-14728/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Audio, size: 206
10-14 15:56:16.736 3481-14728/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Audio, size: 206
10-14 15:56:16.737 3481-14728/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Audio, size: 201
10-14 15:56:16.737 3481-14728/net.ossrs.yasea.demo E/RtmpConnection: Caught SocketException during write loop, shutting down: sendto failed: EPIPE (Broken pipe)
10-14 15:56:16.739 3481-14728/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Audio, size: 216
10-14 15:56:16.741 3481-14728/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Audio, size: 248
10-14 15:56:16.741 3481-14728/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Audio, size: 198
10-14 15:56:16.851 3481-3481/net.ossrs.yasea.demo I/SrsEncoder: stop aencoder
10-14 15:56:16.852 3481-14729/net.ossrs.yasea.demo V/OMXNodeInstance: calling destroyComponentInstance
10-14 15:56:16.852 3481-14729/net.ossrs.yasea.demo V/OMXNodeInstance: destroyComponentInstance returned err 0
10-14 15:56:16.852 3481-14729/net.ossrs.yasea.demo V/OMXNodeInstance: OMXNodeInstance going away.
10-14 15:56:16.853 3481-3481/net.ossrs.yasea.demo I/SrsEncoder: stop vencoder
10-14 15:56:16.902 3481-3481/net.ossrs.yasea.demo I/SrsFlvMuxer: SrsFlvMuxer closed
10-14 15:56:16.902 3481-3481/net.ossrs.yasea.demo I/SrsMp4Muxer: SrsMp4Muxer closed
10-14 15:56:16.903 3481-14754/net.ossrs.yasea.demo D/RtmpConnection: closeStream(): setting current stream ID to 0
10-14 15:56:16.903 3481-14754/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Command (command: closeStream, transaction ID: 0), size: 24
10-14 15:56:16.903 3481-14754/net.ossrs.yasea.demo W/System.err: java.net.SocketException: shutdown failed: ENOTCONN (Transport endpoint is not connected)
10-14 15:56:16.903 3481-14754/net.ossrs.yasea.demo W/System.err:     at java.net.PlainSocketImpl.shutdownInput(PlainSocketImpl.java:368)
10-14 15:56:16.904 3481-14754/net.ossrs.yasea.demo W/System.err:     at java.net.Socket.shutdownInput(Socket.java:610)
10-14 15:56:16.904 3481-14754/net.ossrs.yasea.demo W/System.err:     at com.github.faucamp.simplertmp.io.RtmpConnection.shutdown(RtmpConnection.java:349)
10-14 15:56:16.904 3481-14754/net.ossrs.yasea.demo W/System.err:     at com.github.faucamp.simplertmp.io.RtmpConnection.close(RtmpConnection.java:320)
10-14 15:56:16.905 3481-14754/net.ossrs.yasea.demo W/System.err:     at com.github.faucamp.simplertmp.DefaultRtmpPublisher.close(DefaultRtmpPublisher.java:32)
10-14 15:56:16.905 3481-14754/net.ossrs.yasea.demo W/System.err:     at net.ossrs.yasea.SrsFlvMuxer.disconnect(SrsFlvMuxer.java:88)
10-14 15:56:16.905 3481-14754/net.ossrs.yasea.demo W/System.err:     at net.ossrs.yasea.SrsFlvMuxer.access$700(SrsFlvMuxer.java:22)
10-14 15:56:16.905 3481-14754/net.ossrs.yasea.demo W/System.err:     at net.ossrs.yasea.SrsFlvMuxer$2.run(SrsFlvMuxer.java:195)
10-14 15:56:16.905 3481-14754/net.ossrs.yasea.demo W/System.err:     at java.lang.Thread.run(Thread.java:841)
10-14 15:56:16.906 3481-14754/net.ossrs.yasea.demo W/System.err: Caused by: libcore.io.ErrnoException: shutdown failed: ENOTCONN (Transport endpoint is not connected)
10-14 15:56:16.906 3481-14754/net.ossrs.yasea.demo W/System.err:     at libcore.io.Posix.shutdown(Native Method)
10-14 15:56:16.906 3481-14754/net.ossrs.yasea.demo W/System.err:     at libcore.io.ForwardingOs.shutdown(ForwardingOs.java:128)
10-14 15:56:16.906 3481-14754/net.ossrs.yasea.demo W/System.err:     at java.net.PlainSocketImpl.shutdownInput(PlainSocketImpl.java:366)
10-14 15:56:16.906 3481-14754/net.ossrs.yasea.demo W/System.err: 	... 8 more
10-14 15:56:16.907 3481-14754/net.ossrs.yasea.demo D/RtmpConnection: socket closed
10-14 15:56:16.907 3481-14754/net.ossrs.yasea.demo I/SrsFlvMuxer: worker: disconnect ok.`

**Comment by begeekmyfriend** [comment]
啊，我想起来了，这个问题是RTMP地址解析错误，有些字符没有处理，你慢慢调试一下，或者换个简单的地址对比

**Comment by jamin918** [comment]
感谢作者百忙之中回复我，rtmp://10.8.8.179:1935/ceshi/1，在手机端推流用的也是这个地址，手机端推流是正常的。RtmpConnection.java中onSrsServerInfo方法中serverId = (AmfNumber) objData.getProperty("srs_id");这行代码在手机端没有问题，运行到安卓机顶盒上就报错提示：java.lang.ClassCastException: com.github.faucamp.simplertmp.amf.AmfString cannot be cast to com.github.faucamp.simplertmp.amf.AmfNumber。 在机顶盒上这个serverId获取不到值，会不会跟这个有关系呢？

**Comment by jamin918** [comment]
windows端安装安卓模拟器(android5.1.1)，然后通过usb接摄像头, 同样的代码运行在模拟器上都可以正常推流，这可能是机顶盒的问题了。

**Comment by begeekmyfriend** [comment]
`SimpleRTMP`模块可能关于URL解析写的不是很仔细，所以异常抛出的场合不准确，如果URL某个字段获取不到，那是会出现这种错误的。
