### ISSUE TITLE
在GALAXY Tab 3 (P5210）上使用的时候，无响应

### ISSUE THREAD

**Issue by cl1069573062** [begeekmyfriend/yasea#79]
我在三星GALAXY Tab 3 (P5210）上使用的时候，点击publish的时候，不会调用到摄像头，没有出现要启动摄像头权限选择的框，然后程序就一直卡在哪里无响应。而在另一部华为手机等使用的时候没有这种情况正常使用，

在三星平板上面使用后台会出现这样的报错信息

E/ServiceManager: error in getService
                                                   android.os.TransactionTooLargeException
                                                       at android.os.BinderProxy.transact(Native Method)
                                                       at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:123)
                                                       at android.os.ServiceManager.getService(ServiceManager.java:55)
                                                       at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:1985)
                                                       at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:1983)
                                                       at android.util.Singleton.get(Singleton.java:34)
                                                       at android.app.ActivityManagerNative.getDefault(ActivityManagerNative.java:100)
                                                       at android.os.Looper.loop(Looper.java:156)
                                                       at android.os.HandlerThread.run(HandlerThread.java:60)

**Comment by begeekmyfriend** [comment]
publish前改成软编码模式看看

**Comment by cl1069573062** [comment]
@begeekmyfriend  我使用了软编码一样有这样的情况   我直接在代码里面添加了   mPublisher.swithToSoftEncoder();  这段代码，同时在做单步调试的时候  
走到mPublisher.startPublish(rtmpUrl); 这行代码并没有往下面走，调试界面出现的变量信息如图下
![qq 20160818144639](https://cloud.githubusercontent.com/assets/15069666/17764703/a584337a-6553-11e6-85f4-f40c9b2f8a2b.png)
![qq 20160818144714](https://cloud.githubusercontent.com/assets/15069666/17764702/a57f4d60-6553-11e6-9db1-0842b3bd6800.png)

**Comment by begeekmyfriend** [comment]
你确定`manifest.xml`写对了吗，以及使用的是原始的clone吗？
