### ISSUE TITLE
推流出现闪退

### ISSUE THREAD

**Issue by xiao7468685** [begeekmyfriend/yasea#791]
│ java.lang.NullPointerException: Attempt to invoke virtual method 'void java.net.Socket.close()' on a null object reference
    │ 	at com.github.faucamp.simplertmp.io.RtmpConnection.shutdown(RtmpConnection.java:367)
    │ 	at com.github.faucamp.simplertmp.io.RtmpConnection.close(RtmpConnection.java:318)
    │ 	at com.github.faucamp.simplertmp.DefaultRtmpPublisher.close(DefaultRtmpPublisher.java:32)
    │ 	at net.ossrs.yasea.SrsFlvMuxer.disconnect(SrsFlvMuxer.java:88)
    │ 	at net.ossrs.yasea.SrsFlvMuxer.access$700(SrsFlvMuxer.java:22)
    │ 	at net.ossrs.yasea.SrsFlvMuxer$2.run(SrsFlvMuxer.java:195)
    │ 	at java.lang.Thread.run(Thread.java:761)

**Comment by xiao7468685** [comment]
![image](https://user-images.githubusercontent.com/19483730/100585196-22c55c00-3328-11eb-8e72-4f5c54aa9921.png)

**Comment by xiao7468685** [comment]
2020-11-30 16:09:09.407 29740-29740/com.armslocker I/SrsFlvMuxer: SrsFlvMuxer closed
2020-11-30 16:09:09.407 29740-32415/com.armslocker W/System.err:     at com.github.faucamp.simplertmp.io.RtmpConnection.shutdown(RtmpConnection.java:347)
2020-11-30 16:09:09.408 29740-32415/com.armslocker W/System.err:     at com.github.faucamp.simplertmp.io.RtmpConnection.close(RtmpConnection.java:318)
2020-11-30 16:09:09.408 29740-32415/com.armslocker W/System.err:     at com.github.faucamp.simplertmp.DefaultRtmpPublisher.close(DefaultRtmpPublisher.java:32)
2020-11-30 16:09:09.408 29740-29740/com.armslocker I/SrsMp4Muxer: SrsMp4Muxer closed
2020-11-30 16:09:09.408 29740-32415/com.armslocker W/System.err:     at net.ossrs.yasea.SrsFlvMuxer.disconnect(SrsFlvMuxer.java:88)
2020-11-30 16:09:09.408 29740-32415/com.armslocker W/System.err:     at net.ossrs.yasea.SrsFlvMuxer.access$700(SrsFlvMuxer.java:22)
2020-11-30 16:09:09.408 29740-32415/com.armslocker W/System.err:     at net.ossrs.yasea.SrsFlvMuxer$2.run(SrsFlvMuxer.java:195)
2020-11-30 16:09:09.408 29740-32415/com.armslocker W/System.err:     at java.lang.Thread.run(Thread.java:761)
2020-11-30 16:09:09.409 29740-32415/com.armslocker D/RtmpConnection: socket closed
2020-11-30 16:09:09.409 29740-32415/com.armslocker I/SrsFlvMuxer: worker: disconnect ok.
2020-11-30 16:09:09.409 29740-32417/com.armslocker W/System.err: java.net.SocketException: Socket is not connected
2020-11-30 16:09:09.409 29740-29740/com.armslocker I/SrsFlvMuxer: SrsFlvMuxer closed
2020-11-30 16:09:09.409 29740-32417/com.armslocker W/System.err:     at java.net.Socket.shutdownInput(Socket.java:1502)
2020-11-30 16:09:09.410 29740-29740/com.armslocker I/SrsMp4Muxer: SrsMp4Muxer closed
2020-11-30 16:09:09.410 29740-29740/com.armslocker D/测试: onRtmpDisconnected
2020-11-30 16:09:09.410 29740-32418/com.armslocker I/SrsFlvMuxer: worker: disconnect ok.
2020-11-30 16:09:09.412 29740-32417/com.armslocker W/System.err:     at com.github.faucamp.simplertmp.io.RtmpConnection.shutdown(RtmpConnection.java:347)
2020-11-30 16:09:09.412 29740-32417/com.armslocker W/System.err:     at com.github.faucamp.simplertmp.io.RtmpConnection.close(RtmpConnection.java:318)
2020-11-30 16:09:09.413 29740-32417/com.armslocker W/System.err:     at com.github.faucamp.simplertmp.DefaultRtmpPublisher.close(DefaultRtmpPublisher.java:32)
2020-11-30 16:09:09.413 29740-32417/com.armslocker W/System.err:     at net.ossrs.yasea.SrsFlvMuxer.disconnect(SrsFlvMuxer.java:88)
2020-11-30 16:09:09.413 29740-32417/com.armslocker W/System.err:     at net.ossrs.yasea.SrsFlvMuxer.access$700(SrsFlvMuxer.java:22)
2020-11-30 16:09:09.414 29740-32417/com.armslocker W/System.err:     at net.ossrs.yasea.SrsFlvMuxer$2.run(SrsFlvMuxer.java:195)
2020-11-30 16:09:09.414 29740-32417/com.armslocker W/System.err:     at java.lang.Thread.run(Thread.java:761)
2020-11-30 16:09:09.416 29740-32416/com.armslocker W/System.err: java.net.SocketException: Socket is not connected
2020-11-30 16:09:09.418 29740-32416/com.armslocker W/System.err:     at java.net.Socket.shutdownInput(Socket.java:1502)
2020-11-30 16:09:09.418 29740-32416/com.armslocker W/System.err:     at com.github.faucamp.simplertmp.io.RtmpConnection.shutdown(RtmpConnection.java:347)
2020-11-30 16:09:09.418 29740-32416/com.armslocker W/System.err:     at com.github.faucamp.simplertmp.io.RtmpConnection.close(RtmpConnection.java:318)
2020-11-30 16:09:09.418 29740-32416/com.armslocker W/System.err:     at com.github.faucamp.simplertmp.DefaultRtmpPublisher.close(DefaultRtmpPublisher.java:32)
2020-11-30 16:09:09.418 29740-32416/com.armslocker W/System.err:     at net.ossrs.yasea.SrsFlvMuxer.disconnect(SrsFlvMuxer.java:88)
2020-11-30 16:09:09.419 29740-32416/com.armslocker W/System.err:     at net.ossrs.yasea.SrsFlvMuxer.access$700(SrsFlvMuxer.java:22)
2020-11-30 16:09:09.419 29740-32416/com.armslocker W/System.err:     at net.ossrs.yasea.SrsFlvMuxer$2.run(SrsFlvMuxer.java:195)
2020-11-30 16:09:09.419 29740-32416/com.armslocker W/System.err:     at java.lang.Thread.run(Thread.java:761)
2020-11-30 16:09:09.419 29740-32419/com.armslocker W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.net.Socket.close()' on a null object reference
2020-11-30 16:09:09.420 29740-32419/com.armslocker W/System.err:     at com.github.faucamp.simplertmp.io.RtmpConnection.shutdown(RtmpConnection.java:367)
2020-11-30 16:09:09.420 29740-32419/com.armslocker W/System.err:     at com.github.faucamp.simplertmp.io.RtmpConnection.close(RtmpConnection.java:318)
2020-11-30 16:09:09.420 29740-32419/com.armslocker W/System.err:     at com.github.faucamp.simplertmp.DefaultRtmpPublisher.close(DefaultRtmpPublisher.java:32)
2020-11-30 16:09:09.420 29740-32419/com.armslocker W/System.err:     at net.ossrs.yasea.SrsFlvMuxer.disconnect(SrsFlvMuxer.java:88)
2020-11-30 16:09:09.420 29740-32419/com.armslocker W/System.err:     at net.ossrs.yasea.SrsFlvMuxer.access$700(SrsFlvMuxer.java:22)
2020-11-30 16:09:09.420 29740-32419/com.armslocker W/System.err:     at net.ossrs.yasea.SrsFlvMuxer$2.run(SrsFlvMuxer.java:195)
2020-11-30 16:09:09.420 29740-32419/com.armslocker W/System.err:     at java.lang.Thread.run(Thread.java:761)
2020-11-30 16:09:09.422 29740-32420/com.armslocker W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.net.Socket.close()' on a null object reference
2020-11-30 16:09:09.422 29740-32420/com.armslocker W/System.err:     at com.github.faucamp.simplertmp.io.RtmpConnection.shutdown(RtmpConnection.java:367)
2020-11-30 16:09:09.423 29740-32420/com.armslocker W/System.err:     at com.github.faucamp.simplertmp.io.RtmpConnection.close(RtmpConnection.java:318)
2020-11-30 16:09:09.423 29740-32420/com.armslocker W/System.err:     at com.github.faucamp.simplertmp.DefaultRtmpPublisher.close(DefaultRtmpPublisher.java:32)
2020-11-30 16:09:09.424 29740-32420/com.armslocker W/System.err:     at net.ossrs.yasea.SrsFlvMuxer.disconnect(SrsFlvMuxer.java:88)
2020-11-30 16:09:09.424 29740-32420/com.armslocker W/System.err:     at net.ossrs.yasea.SrsFlvMuxer.access$700(SrsFlvMuxer.java:22)
2020-11-30 16:09:09.425 29740-32420/com.armslocker W/System.err:     at net.ossrs.yasea.SrsFlvMuxer$2.run(SrsFlvMuxer.java:195)
2020-11-30 16:09:09.425 29740-32420/com.armslocker W/System.err:     at java.lang.Thread.run(Thread.java:761)

**Comment by begeekmyfriend** [comment]
See https://github.com/begeekmyfriend/yasea/issues/792，不是立马就重连的，起码等待资源释放干净，异步的话，可以用mHandler.notifyRtmpDisconnected()通知主线程重连
