### ISSUE TITLE
短时间内多次重复推流出现闪退

### ISSUE THREAD

**Issue by xiao7468685** [begeekmyfriend/yasea#792]
│ java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.github.faucamp.simplertmp.io.RtmpSessionInfo.addInvokedCommand(int, java.lang.String)' on a null object reference
    │ 	at com.github.faucamp.simplertmp.io.RtmpConnection.sendRtmpPacket(RtmpConnection.java:497)
    │ 	at com.github.faucamp.simplertmp.io.RtmpConnection.closeStream(RtmpConnection.java:339)
    │ 	at com.github.faucamp.simplertmp.io.RtmpConnection.close(RtmpConnection.java:316)
    │ 	at com.github.faucamp.simplertmp.DefaultRtmpPublisher.close(DefaultRtmpPublisher.java:32)
    │ 	at net.ossrs.yasea.SrsFlvMuxer.disconnect(SrsFlvMuxer.java:88)
    │ 	at net.ossrs.yasea.SrsFlvMuxer.access$700(SrsFlvMuxer.java:22)
    │ 	at net.ossrs.yasea.SrsFlvMuxer$2.run(SrsFlvMuxer.java:195)
    │ 	at java.lang.Thread.run(Thread.java:761)

**Comment by begeekmyfriend** [comment]
排查一下关闭连接的时候是否[reset](https://github.com/begeekmyfriend/yasea/blob/777c9440836d766e0bcb3896c88d2a245ed34fc0/library/src/main/java/com/github/faucamp/simplertmp/io/RtmpConnection.java#L376)完整，不知你重连是异步还是同步，异步的话，你可以将mHandler.notifyRtmpDisconnected()放到最后去通知UI主线程可以重连了

**Comment by yitongUp** [comment]
@xiao7468685 请问你解决了嘛？就只是把mHandler.notifyRtmpDisconnected()放到reset()方法后面嘛？

**Comment by yitongUp** [comment]
> ```
> │ java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.github.faucamp.simplertmp.io.RtmpSessionInfo.addInvokedCommand(int, java.lang.String)' on a null object reference
> │ 	at com.github.faucamp.simplertmp.io.RtmpConnection.sendRtmpPacket(RtmpConnection.java:497)
> │ 	at com.github.faucamp.simplertmp.io.RtmpConnection.closeStream(RtmpConnection.java:339)
> │ 	at com.github.faucamp.simplertmp.io.RtmpConnection.close(RtmpConnection.java:316)
> │ 	at com.github.faucamp.simplertmp.DefaultRtmpPublisher.close(DefaultRtmpPublisher.java:32)
> │ 	at net.ossrs.yasea.SrsFlvMuxer.disconnect(SrsFlvMuxer.java:88)
> │ 	at net.ossrs.yasea.SrsFlvMuxer.access$700(SrsFlvMuxer.java:22)
> │ 	at net.ossrs.yasea.SrsFlvMuxer$2.run(SrsFlvMuxer.java:195)
> │ 	at java.lang.Thread.run(Thread.java:761)
> ```

@xiao7468685 请问你解决了嘛？就只是把mHandler.notifyRtmpDisconnected()放到reset()方法后面嘛？
