### ISSUE TITLE
调用startPublish()方法闪退，

### ISSUE THREAD

**Issue by 1403851384** [begeekmyfriend/yasea#795]
Process: com.leimon.leimonbot, PID: 10535
    java.lang.ClassCastException: com.github.faucamp.simplertmp.amf.AmfString cannot be cast to com.github.faucamp.simplertmp.amf.AmfNumber
        at com.github.faucamp.simplertmp.io.RtmpConnection.onSrsServerInfo(RtmpConnection.java:638)
        at com.github.faucamp.simplertmp.io.RtmpConnection.handleRxInvoke(RtmpConnection.java:591)
        at com.github.faucamp.simplertmp.io.RtmpConnection.handleRxPacketLoop(RtmpConnection.java:562)
        at com.github.faucamp.simplertmp.io.RtmpConnection.access$000(RtmpConnection.java:44)
        at com.github.faucamp.simplertmp.io.RtmpConnection$1.run(RtmpConnection.java:151)
        at java.lang.Thread.run(Thread.java:929)

这个是我的推流地址"rtmp://222.128.87.6:8001/channel/2/123456?vhost=tv.ossrs.net"  定位到serverId。

**Comment by 1403851384** [comment]
其他的地址有的不会发生闪退，有的也会发生闪退

**Comment by begeekmyfriend** [comment]
`SimpleRTMP`模块对文本解析有误，请调试一下，我手头没环境，抱歉～

**Comment by 1403851384** [comment]
好的，我继续排查，谢谢

**Comment by begeekmyfriend** [comment]
欢迎PR

**Comment by 1403851384** [comment]
谢谢指点，问题已解决，是srs配置的问题，推流推不进去，刚刚用ffmpeg推其他视频也不行，已PR
