### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by iamjpsharma** [begeekmyfriend/yasea#828]
java.lang.NoSuchMethodError: No interface method setParent(Lcom/coremedia/iso/boxes/ContainerBox;)V in class Lcom/coremedia/iso/boxes/Box; or its super classes (declaration of 'com.coremedia.iso.boxes.Box' appears in /data/app/~~14QZvnvkgEPXpVwzCKF6jw==/com.novotraxcorp.bodycam-xmdtKVD3BePHCVr_SfgF8Q==/base.apk)
        at com.googlecode.mp4parser.AbstractContainerBox.addBox(AbstractContainerBox.java:94)
        at net.ossrs.yasea.SrsMp4Muxer$Track.<init>(SrsMp4Muxer.java:575)
        at net.ossrs.yasea.SrsMp4Muxer$Mp4Movie.addTrack(SrsMp4Muxer.java:691)
        at net.ossrs.yasea.SrsMp4Muxer.record(SrsMp4Muxer.java:127)
        at net.ossrs.yasea.SrsPublisher.startRecord(SrsPublisher.java:201)
        at com.novotraxcorp.bodycam.activity.LiveWithRecord$2.onClick(LiveWithRecord.java:152)

  minSdk 21
        targetSdk 30

**Comment by begeekmyfriend** [comment]
Maybe SDK version issue? You might check out the source code of `com.coremedia.iso.boxes.Box` to see the right interfaces based on your SDK.
