### ISSUE TITLE
空指针异常

### ISSUE THREAD

**Issue by tianguo1314** [begeekmyfriend/yasea#856]
2022-12-28 15:09:19.155 32386-6668/com.north.arrow.technology E/CrashReport: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.media.AudioRecord.read(byte[], int, int)' on a null object reference
        at net.ossrs.yasea.SrsPublisher$2.run(SrsPublisher.java:107)
        at java.lang.Thread.run(Thread.java:929)
2022-12-28 15:09:19.155 32386-6668/com.north.arrow.technology E/CrashReport: #++++++++++++++++++++++++++++++++++++++++++#

   if(mic!=null){
                            int size = mic.read(mPcmBuffer, 0, mPcmBuffer.length);
                            if (size > 0) {
                                mEncoder.onGetPcmFrame(mPcmBuffer, size);
                            }
                        }

我对mic进行了非空判断还是出现了空指针

**Comment by begeekmyfriend** [comment]
抱歉已经不从事安卓开发了，偶尔上来看一看。你的安卓SDK是官方的还是定制的？

**Comment by tianguo1314** [comment]
不是定制化的  就是平常的手机

**Comment by begeekmyfriend** [comment]
安卓版本变化很多，也许我当时的SDK版本落后了，你可以调试一下`chooseAudioRecord`函数，看看是不是适合你，如果有改动，欢迎PR
