### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes(java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by ashish967** [begeekmyfriend/yasea#88]
java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes(java.lang.String)' on a null object reference
                                                                     at net.ossrs.yasea.rtmp.amf.AmfString.writeTo(AmfString.java:60)
                                                                     at net.ossrs.yasea.rtmp.packets.VariableBodyRtmpPacket.writeVariableData(VariableBodyRtmpPacket.java:71)
                                                                     at net.ossrs.yasea.rtmp.packets.Command.writeBody(Command.java:74)
                                                                     at net.ossrs.yasea.rtmp.packets.RtmpPacket.writeTo(RtmpPacket.java:32)
                                                                     at net.ossrs.yasea.rtmp.io.WriteThread.run(WriteThread.java:54)

**Comment by begeekmyfriend** [comment]
How does it happen?

**Comment by ashish967** [comment]
It was happening because I didn't know  how  to specify stream name in the code.
but later i figure out that i should append stream name in the end of the url with "/" prefix .
Any way thanks 
Can we view published rtmp video using this library ?

**Comment by begeekmyfriend** [comment]
Then you need a player like VLC or some others which could resolve RTMP.
